apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:APLG2pGgobgxIx9petMwT+aM8wETzlvtdqonBRAwo6vTiOUgyYe9TQ==,iv:m5ayHMN+txAVoIyRR4WmX/MrdEhb2Ou5owLFBA80Dvk=,tag:/nRxBy5eRyKM8aV/2YH5Tg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvamhkNnpUdGk0L2FDMy85
            TE8yQXg4cUU5YmxRR2drb05KbWNYTDNOS1E0ClZFNHgwSHJGSS9nVTRDZzJMTkRk
            MnN6S3F1T0k0SlhoS3NyYWcwck04NGMKLS0tIERPSldXeDlWaDI3L2JnalRsV1kz
            djV2UC85R2EwTFh2UTdrQjlObUZSd3cKJYUk62RfMFGY0O6hf9m9130aP1XK31MS
            0g6xRhKrtYeivOVGyEN21vBttDTDt0YoovdP6a9WwUn2uD3xsAJs2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T07:13:25Z"
    mac: ENC[AES256_GCM,data:V927XBSSXjhfM8Ne1mkzUsCbH4Wi/tfu7bE7JLoTurIwOb041QUZDn0N+ohs6m6onjvqrY4LuvSLmyJP/Ug0wXjiMiYuWXKj9UW5zDq4JqjtIDxdj6xn8mlw2Oq1CAaHjWoLVbG+QALzfOUHrdwZZsYM7bqJe3gfUVGFrkZRfAU=,iv:0332Ytlh/uRGWRfcI9/kCyIm4IQsjr1zev2CUw8Id2g=,tag:+f3yGYxMcec8VerOXTA4hg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
