apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:LyCES//754KtBJIm9eZYM5tHB+GQpy+IF0jmqxdgoz3iUkAizws2dQ==,iv:0wy+JswE0ZNv5BeZjKgrZzQFAUO+OcXtvzoNLC6fkO0=,tag:lMVGxiKBVBKTfzfui2nZSQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOVBqdkUybmZqNTd6Wktn
            eW1xdHVSR3prZXByLzJNcTNIMWlLWWxBOW00CmJvTDJTcE5rSk80dndWQXEyZzRK
            ODJsUERjWnM1d3I5QUF6bFRSbURGSlkKLS0tIEo2K1IyTm1TemZyL0ZBZG1ySFBi
            cFZRRXZTS2orMkZEQmFnSHdYZWdLVVEKEyuVwZZTCf1rckkpfDrhW7S/2LGTNzq7
            tZOrZENUg2OUjX/xSBIbjfXAHOLtJjdpRz2v+IH2YHyNtzoTvVTzug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T06:56:30Z"
    mac: ENC[AES256_GCM,data:uJB4Xi6t9hd399+d7so4nqH9iJpSfeD5t24Po6Ic7BskkDRHiYxxAzSBETtuip9v+3jZvaB8xaYhlR453Y8BRHRJQtX945MINH2BmqQM2Zz4dHjon/ch9U+7epugEkJkXqMqdZ8O0X82j9shQmA2rSgNQo0CQMmXet7SBySwnQg=,iv:MaIl03VeW3X598oiig4eZyccfouPFGVXM2pu18Q9D40=,tag:qxe++qzt/gwyMeT363u4Pg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
