apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:1s0JZBFVMxpI/N0y9N9C/e29aXYcyHUO/Q9fuCJhft70ks4bnDp92w==,iv:odPODBAQlPNB4TlHzwN8NkQFuubBeSIIMse5ThCfgPc=,tag:Bz4YyNkcthfNgkOkANT5Pg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSzdZdkpNbWxyNTlIYk5N
            a05kNXRUalo4WlBkNktNYU0rVHpsOTB0dlQ0ClBpVUpFTU1kWk5nOHdVaWxsM2tW
            VU15dTc0NytBcXhTeDUxUnphSm44NFUKLS0tIHlaczdqSE13dk5sYVl3enl5cWV2
            UDltVUJLVnFMVU5UR25HZGFSMWx3TG8KxE0aHPXRimShjMH988q4hnx3PKFOAdzE
            r3aiXaOMP6FoxCK3fp+vIYrmH1VqIKh6bOp/fgnXiT3GQVhH0tR7jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T20:00:24Z"
    mac: ENC[AES256_GCM,data:JDS6EzrD6teIq0xaAp2rTiNyHfE9GWaDz6GyYOoiP9LLmjDQQoBLIx7XuFBAgCl9bweoDIsuDCjLUAiOMGZWDDl3szL7HjtFnHF3S60Pmhey8CcrrMVp8v5Re7xQ4iotkWgB0D5v/pfUK2zABTeaWJuoCu24yUHOYByZHw84NJs=,iv:UXdYgqKGKGBc6NW7GWrMIWuXXnjeCSKDvhM6cTirm1s=,tag:ZVQAGrZy4knK/B9cSqAGBg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
