apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:46jWgCbHTyVDYjyrgY73mxpXdpxjWpPmrVAQ4rorX7ah84xQ1PKYew==,iv:BKUFpRGov7zZC7cTjDsVQ2eLHEJYA1EBBgzEtmgZ5JI=,tag:Cqe5MxPv/ZNQWHK+j0iMmQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMTJFUzBRdGV5dnlZMGx1
            K2lxelZIZzhrNlNBRFEyK1hCSGh4RmhWcEdJCllKLzZOc1AzNVVIM1FrQm5KSndU
            ZGZqS1hKU20wcUdZWllqR3ZlSnJaNEUKLS0tICtOaGZZWWtkaFRMQVQwSUc1UnJq
            bjNQM09uYmRhMnhBM1BGZ3pyNUdXSXcK7Io4i0kYcN+Xhhh+2SMj5cxsRpX9FENs
            gcGCfzt1DgW01COCfwwvcCJhQ/y3K08k1xCBzzUvlflsLacq9QYL5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T11:30:20Z"
    mac: ENC[AES256_GCM,data:2CZRVdtJ61LGP+Lhaz7BZc6ib9iCmA1iIcEHOUZQ+sYFy2T+5OY61Bdi/MJNzZY5xrOF9UC9zGL6/cmwvPEapHZsaZQMB2pxmjiWdvdxyItDL0BLYpNsB2l3XKpcQSu6CH7xn4xZVCmzvvi7KA9fBsGM0gozDSGedf+Ckn8UAqE=,iv:pXOqdKxSZBdz+fW/314xuSnMIL/XO4tLouFiCDYy9hs=,tag:hEzDq3RdpxZMkA3OEA28lA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
