apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Zgw95y5ZXIstRneutseYGroX88jtySVNT3dyrbQWpQavTXH2r7b3Vw==,iv:9pqbV3rQ8sWQao0qXqawDTn62IQz7lMphhGqOSqaQFw=,tag:vP7MYGRXPbbMBnrLzEgB/w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTDN3VDZLQVUvYnBaenZO
            V2pGZFBRMHdMWjFqTHZxWDNtUGVaQWhOS0RZCngybUpaN0JPSWtkUDc0ckpNOEFv
            SmdQa0Y3eUg4YnZJaHVjcXJkUkhoWDgKLS0tICtTcHBYYS9uNU5NeUNzdDB3MU5K
            NTRBQVU1ZHc4YjBiUTJHOEkyQkpLZ28Kx1aDbGHUmUYltTSPdgV4hwUbSJAI30LC
            arJLNAaz3/7N2DZSzNP+Qr8NtI7CJKxRN83TzkHSZ+PYBc1/nIGgTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T19:51:47Z"
    mac: ENC[AES256_GCM,data:Wr7vYKNjxikK5fk6PMuukoMPNwuVVCX9NDHhdALnbfRQstJHUK9gikRYHczXWVjtXFu23ZKm6YpXleA3djPl8ITux5TrlpbggzmGEsu225b86gfArtaNK2Ryql6Ku2PVU5j8RiJFTBJxvsFve2mouN3+hVIJ5MW5BEuGEd70+6Q=,iv:5cY6D9JP7m3Qu1G0cvNm6kGca3CMHXB15SSdvM9NjUk=,tag:20v4RhIGmYpjezDQGkKC8w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
