apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UzvpAfDhQi79b99LBxKQm7Oca1l28wISjOn2wpZW2Za8qE7fjEjrZg==,iv:FufzGsH543LFBiPNM/V6MMW6T683Tq8oSjEwppbrN4k=,tag:AOCOfXcreHCxrBnVp3qSsQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRWJPYytZUEREbGRNS0Nn
            a2g3SEdPR0x0dFMyUkNDdjEvc3MzRmJWSWdjCkh0WHFiWEFSU2x3RlZXM2NKelpw
            ejk5bFg3WnV4VHFSaHIxanVWbXd2dHMKLS0tIExtMGlHNDZxT0RSaG9reGhaOG9D
            Sjh1cDlDaTN4eGdZVFNyd3lRbUJzbWMK8fERdkZfK1TA6v8qfki0Yf5zo0jz4e1L
            h5scPYfx5I2+G8TEWWfAuylcZBnTe4vq1kDO3ooSkhaqfsmqr3gUCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T23:54:58Z"
    mac: ENC[AES256_GCM,data:UuATrN3lEe34vDNXlGXWUMWbNYAXZpAa5wM1OUGorCdZyAxp5bsue08RsNV5oL7Pj46LQzsTChTcjGFr7+B7h1d44n61OLopxfJ742ODKzbS1oC+JY5OTCHnHy8bV2AUDoZdI9eZm+QdBlP9MpCdpWqh6zwmIz4S3sTrbCQKynU=,iv:nQoyYg/f7YRWgIO2xSk4sy5J24kHH19PSuT9MWXutPs=,tag:Iz9NXRypqqsg/n2i8IG3ig==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
