apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:HBWJP97AVaJNJNPj5fbYNM8M4c8Qa4dBvqYe31lFh8ByX2P7lRyt1A==,iv:nBRoHjdSfLvWl0IPquWBWJ7kCvorZ7j/LWD84gCd5NI=,tag:IbU+a5cnSK0JW3I4ukKzdA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cm5jTXZicTliVVRPM2k5
            REwzemhkU0dHay83R0hsbHRDdUtzaGt3WVVNCk5CMFpEcmJEQkU2MStMOUJwRzRl
            UFpDaW9Id2NuNllSMWROcjRRdzZrbjgKLS0tIEdwTGo4WGFiYU5YNlN6Yi9XOFFn
            SEpveVVWS3lscnNBMFArbnlFL1ZRL0kKTffm2OggCCHhFVfQ+uDQ2k29ghDaguJx
            ceq4UiM2cOUyeyE3gAa2r1p7U7kEKTnKrDR8wDOcq3an3pUejkrSew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T07:29:53Z"
    mac: ENC[AES256_GCM,data:enbqbHS8p1tU/Idm1Z2jJmm0SJ+ixqqc4QxN5Tmojp1T+IRMsABeWtWiFYbrdvl5uhy4U+7tQRXVV+fFA3UAM6J6tVqpY5vLhSV+l50wczvopSjK0VItazr5O+5P18NiK9YSKtFyqiGRalxsKkYQa/rmf4kpHUVaqmDMSph8GrY=,iv:YDKn8ZTPMH2faG7UubTOwrA5f7Z/5DpjXhdP7jTpRNI=,tag:BRcDtp1WJ+2kcrd9jAhb8g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
