apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:bbxz5wYDlzPSrLZh4OmAkUWVFF2SBmUktt/lggcrzVhLL05gBYILpg==,iv:BD0S7eiWkf4OC61RG6bzOjO0PuLwjIyMFA94lWK73tI=,tag:Wl3b7dNg3ttxoNTxfY11GQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMVdjL2YwRStnUER0RHdx
            dFFjVTB2QnVCQkRNYVg1QVd0YStQUldhRzJFCjdjV253TVQrUFFLTDNvaUM3ekRn
            Ym05a3dOUVpCTW5SS2N4WS9rRlFzTDQKLS0tIEl2WThFUE1YNVFycUV2cktKcjhD
            L0dMa1RwQTZhN2JjeUdyc20zK1ZSUlUKUDc26YARoAhSEkUoQhxWXDrCXVzXZ2nD
            9qxNAT+2RJtj/mJ4F7IXcWZTgl5LJeSglT4LnfJrkfvBGxSXiy8OEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T20:51:38Z"
    mac: ENC[AES256_GCM,data:1H5XfFMqxC3yUWAda5pIVdECyjPdcfmtBxTIDULuWX5K7fl+l6OdUDJv6YogQzV/co5BL9UrxN5jmVLZGJ54Ue4o4kywzjm7tPcqycrDUPyU+Ou+f2lHKo8+tblRlUi5gsk4H9ytYbdRDJUmGS534hz1I8EcXAEz7LQT4MZ4SU4=,iv:cYRO9ykV+CVlDiu/OcTQLk1/VlcQYCjTT0zM45Yuwjs=,tag:L+hCL+IVJY20arZSUA+/XQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
