apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OkIewnNFqyDD6yCTQ/v9EiYoibfsUFyulke81ht8Nk8ZdrFCNkD7xQ==,iv:Kvw25J7eNZnZQzsmH7KZHgoAD4vPbYrmE8rnF0gRq4w=,tag:VxNJ7wDclWOyM6/SJtnJuA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RUhHcjkxakRXV1FDWTZD
            MHovT1BYUGliTU1pcTdnQ3pjRUJtYWFHWUU0CnZlQXlDb0psdVE5WElNREJNWTNB
            TUdjbHZTSDNqZGFOVHZqYlBEMmZQZEEKLS0tIHFmOTlUN2MzMWpsTk9WUXBTSUpZ
            cjExZU05RWh6NzVoME91dEo2aHlid1UKB3jHQIcR5XkwDwf9tJqIDBwGDVzd5hAW
            zQIALElEdF8vcRhLXzvBxFsLB3NhSFoEAYYUvsYe4qUJjVMBeaXP3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T14:35:10Z"
    mac: ENC[AES256_GCM,data:jG1vktd7UpoDYtoDphCjJlCCSdjzGoMB6C7vSCZr3OKCTClI6EcLpF9TWs0Ut+sw6F9qagQoReN2X/BCkYDhWA20AmRbALFSz3NxEkZSveK+TXP0pyO8lfvk9x7V4ig1WfPfjU9/c54+SjFgzCIvdemFCL2zBUO/HQnww2T5Ans=,iv:/FTq911s2rktu53avwsiJjo+iw3e6WuEbony3cS2CSE=,tag:/lSyTCfVmPULdYEApm8njA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
