apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:+mjD8Wkp/49W3IE4TvN3FcFYQuzi9dNOeb/HV9w4+P5VVXy31eI6GA==,iv:8aRylrWbOHOpL/+CA0CsR/c6WTV1WK5swC5kOOKBfgg=,tag:uhfLYwq4A2R15GaTUPLcPg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWVZ1WndsZlpoTE1PZXh2
            OTVyUWFVWDB6QXRKNUpjL1FlUGhuMXNod2tZClprUVYrTDlOaVZFdDlkVmZmUi9j
            L3JjdHNwRndyenFBSFhxN2tMWFFEVnMKLS0tIExFVUYrT1JuOVVXMldxTnBaRmJS
            dzVFZkF0cnZrUUNCa2VaZVZxS0lKWkkKUuBI7TFdrq3arX8rBcN9Vk9kLz/uLEX0
            2P8rOz2Oq1EHL6HfvtK4GQdGx7xGIGJTnrxtSr1HQUDZHeBnyXzYZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T22:04:17Z"
    mac: ENC[AES256_GCM,data:HfPLNJBf/ai42GTW+hbqNjpGsSvY2jucvqA4IE4ULvCFcKl3o3eTjGSioi/2UzEESM5gO7HmVlHam69gCEfUKe1AVNNjrXYxrK+Oqcma/znww9E2Es/eBipe4zLkBkthD42WrLKi7874zwC0XNYqRImUVVfSZEHPyUNGb/AmQWw=,iv:r6z4RMr9rdVRBGU6bUySdnGoAtR8lHQetKQvWsheOgM=,tag:AAjvcBqMKTCEix6wgZd6gg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
