apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uNFuBknrZRmK2O9z89kd8DVBHysFx//ijOwg1lGD+1R4Aw22aB8s/A==,iv:WHdvI2YmIO3anocltZFFTdIx+B3uabTWN5sNPmaSp8k=,tag:sIS5/UCwayRAdJaQyy2Sgg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMk9sZk5Da2hEYXB6a1Mw
            c3RaS3dRaml2MnhaWThoZ2JYcFBzSlBFVHdnCmxDN25RMkJNdGlBeUoyQzJmSHJ5
            SDdJak4yWjZodytBdEFzOFd2MzVHL1EKLS0tIExHRkZlZUdkaWNEREhCZDQrZVVB
            a1NnNDhUVjFyeXZEQ0hTSStNSjd2SkEKenaB1e9z6ykialagIT+IFLr1hBxmLPFG
            bd8k7X+H2266rpxUxh4kCIBIQ2bd2ckwTGrozKBH2LhSU6AEH1de+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T11:28:33Z"
    mac: ENC[AES256_GCM,data:5Ue/kq1GWQAFNA06OOSnVyKt4Y/3JKpaL8wz4R2b0qofHmWr19qhXZKXA4qcekf46USV7emhNmo3CauMwib87/+LwzxaHHdYq0XIzCDeXydAX3ZsiJX+vKwtiLj/1Iq17FlbDFJph6OiwkYIuV/FbQOhUYDgXdy8qJbfwiQ7/68=,iv:tx4u7Q2my7Qi8Yg3XRq7lSyKLdAU5FjgphkWTekh3YU=,tag:JMfw+Boh2N5G8JSznkOpbg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
