apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:OdYiMtlSx6EaXVBc9rfNJ4rc3BjPQEU34vsJWXWdtSAS8bJ9EcQgzA==,iv:+mDPr2P5Fg28XcfNNYujm+n/L8Csy5urcujmOzaNqos=,tag:yrTSZuFqc2GWoqoj1e9i+w==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleEpPRVA1ZS9KNU93WnYw
            d1JGam9ZUUNoOE4wR0FmazJkc0tSYWp4eFYwCmpNa3h5UUhyV0ZmSTJUVHkyVTlH
            UEN3bkYyR2lsaTZvRG9RMUFONFF1NDAKLS0tIFlFeEY3aXpjcUFQeTJ6MG9BUzFR
            ck5QSWFuMFFlQUM3V0hWUEc1RDNnK2cKYc6fc1TS5XVZ3yj5Bb5MKer1Zr2DXK2Z
            n7KzeFazLrXPwE+RP9zwbh4vlKscz2UL9bhE1ilznaKSVw3CRIwGSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T11:56:39Z"
    mac: ENC[AES256_GCM,data:D3UhL8UAhYvD0ji6F5RZeIrgnoW0r26wAJ+wSYpOEjcrx2QdPa99jTdF9I5c2jxFfc3JfzBOx7mgFcmrBqmNK5uTPX80q8nqGil6Eby4jjiJgfnPK/AdNRdKqnlxGa+AbBtGc5SVvyyUvAv67zuIL5AjhPs+dO/3Ex30L+ABaK0=,iv:jPDYkTvK6W6vExad77qkdkhMwwefQS1rJGSe3YL05HQ=,tag:Ou7BWbH4SEyab7EJBM/5XA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
