apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:jcFI5DA3+K7QFhSthGAYdO2eNqQLIDnHM+zmGMwk2y227/jinj1iaw==,iv:Vrvk4CQRwxu8mLzqMlWvXiVs+nma/AorEk11ovjL5C8=,tag:JqaxZRY/FJyd0vyPYk3qiw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbDdiaTQ1S2NYODR6UlIw
            eGtPNUIyUWQyekdtUVM1VEwzekpnWm4zQkNBClViZW42cmhNdmhrNG5YR3FobVdp
            bEg1Q01iWFQ5Tlk1Um95S1BVR0lFMzAKLS0tIGFUWGYvRFcrOXhWZVQ3Ulp6YXBj
            V0s1ZmU0R3VocWJKaWkvMnBUdW5zVEkKXekpPAtoG9AkRPNw1lHdocfN4OlX4/9K
            5ZRzPWKXTpb+W1fThTOlbbINaQXtFNbZnXa+axeRXbfyB0xeZ6Ew6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T06:05:16Z"
    mac: ENC[AES256_GCM,data:ygC6p0VT8UXw/oX8HHtH24c+pguFKknopG/YX7KLFXG0SbafBuEDE2wji8rnEmxmEui+gyxpysjS4+0sY5BFxsXjTOB01FXSVe3IX8TSV0jhy1SYe62qAaAk72il9XF+JwsQ96pib0hytZcoiTYrJz47lpyOyjybmaejaCT5arw=,iv:Wphlk9UQm0SRUsNqkeWr8eqPK2yFPn4EgaH5YVCgVk4=,tag:5SGySopZpqoXHG7yygHQNw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
