apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:VN4J1ZrGIsYNQdYi9KIS0WrUsayPtn99ussQO7qb7TJB0H2JSUi3ig==,iv:s1/feZexNKPBUHx/2cuneTlkYDUlUs8CzCvl4oV00XY=,tag:ZzgYoS3TtqQkXJi4u8s7kw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNVAzU0thZ293c1g2WmtJ
            aGVkRURXSEpoRUdXdzhGTm9vcW1PYm5Jb1QwCnpPdGtoU3ZSRW5DZkJPbytINStp
            WXIzVVp1emtMTy9qRE5SSHE4ZmpkMjgKLS0tIElGOExOdW54S1VlUnpnRXJLbWxH
            WGFHcHdYeHhicDluOUIvRVlIazUybEkKcD6+9UY9n1nGTFEBhLAjLtDiVdNxuReH
            BK8sm8skevI4/XqtmaRBY+cKjKK3mfhGdTP1fz2qmrItmq41GCuhxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-08T12:57:26Z"
    mac: ENC[AES256_GCM,data:oR8xQf9G967Zk3rP/SOvPZh7XU4Aa2YZBAiEhYWgaqtnfeIRN+EvB0fCke00RMB0dOOMa+VDd9fwNHxwoTkfra+6s6PF9RHDmf6YQktBopeg62huz9X7RHozeUq/9yxcaxL+E2jajbIq2cerTlYOSssAOj81HpUmUO5BAUCPdIk=,iv:x6WvVMyUlm25mdEnWHNjml+H5wdaLg9iDJlX/LHPkH8=,tag:hWfDU1AFi9DsgCBwoh2WWA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
