apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:HsibHueI5oD9L+BMgWFOUoJd0IoFkRSegK9wrRFzdJXjR+xu1HNwEQ==,iv:JkQA361bddZkP7rnMkwNpP99wlAs9qMiv81MTJ4Jh1g=,tag:QGEmOjCtA9YXuORmoCunDg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVEVadW82U0JpTU44cU5N
            N2hzWkh6SXY1dW9ORDVGNSttZDI5Si85c1dJCmo4a1lHRFhSU2dQczVhbE94MjEz
            YjJCNHRuNEVVeWpvQ0ZkbjR3SG1FMVkKLS0tIHdXeUN5VW9OcmpKYXg5RndXTWNC
            WWhBWTJXSGpGYjhXekxmY081Z1lLQ2cKUc2Qq4/P4bWPPq36q5+57UGLkQ1n9XrQ
            f9ths7cbnVIVK/TDRf6IEC+zEgMU3YSKVzih1Zo8tplIkIa3tT6kTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T13:47:52Z"
    mac: ENC[AES256_GCM,data:VBzREmTceIe6SRKi6tEHItcIHpY+8KqFYMjZVYQYR3I0h+HsvKfCtXoeRaMEro+Bwu+54ZD6x7y9ZVFXVSRRnzbSZdR/yfjq+dr/CILGC2t780KNMIBUvk3VAeCqM+31VqipihoGD9yQ7ltLyWP+96dKXn6FP81D9rR0L/1G4SE=,iv:1JtpceV8Ti7abi+0OdPhhUCHvCLQ8a8BsAx/ZiUhYRE=,tag:rthHV9gdx0z/bvVLQaFClQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
