apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ln4SbOz9FO19J9LHcbrS7/yVVJ+3jLbf5rpSxQnbL69dgH5Dq4dpPQ==,iv:H4f4A41OjW3cf8d2dBL6frn+UsBWOZ2PnJL32EH2sF0=,tag:gr4ZtoCV76Xcrg4cEAMneg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYkxyZmJEY0g4OVp0SzZW
            U0lUL1lKSXRWQnpmWi9NVnlRaFNRS0lZSW00Cmw2SWF2bmFtY0hOM2JjcVRodDZL
            TGdFMFlDRmd3RXp1c0F5NEsrMFVMeDgKLS0tIEpFQnJqNjdHbjRKSm0vd3QvaHAz
            aktDUGk5QWdwSmg1VEpOS2t5YldjbzQKm+aHl8DsPDyD2Z3/nXs3RAaLgwsyxlUf
            qict0qU30lGmqrwQxbfB93lYNP3ktOEX+wkeCYlv4prow3sgbxXV6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T14:50:51Z"
    mac: ENC[AES256_GCM,data:9d94nntWG3dFVYGwNXyHRI8LSvADCYASBtQEtoUhSzeNFvo4ySdgc+K+AJeKtrZqV1ygLrIj1kBCzOr0E/WTx+71f+NSS7maFqhTnOtUQMlqRcHPGHHdeFrnGjZaDVMlKlqY9GHNwrUsh4btu/pc2gOFY88QdCz9Pc4oGcB+NpQ=,iv:W2AI5ql8KsQCmAyybZdvKtoqD/HGiR40IRlvqFwLL20=,tag:ZRAUbAlb+10RY2e8YMmS6w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
