apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Kk+dSQyybzHdDOsI1En/dn31yw+nJ9pqgelxATh4VetiRQUJjP746Q==,iv:PAOvuFhlw/jyhQ3ot1BUZVXsWbBcvzAZ9E7GCwQIkoY=,tag:aXd1hWUIvqcFzkULOhAT7Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SUo0c3VNN0FGbG56Rktu
            Wko4SzV4NDM1L2FjTndhNUgrbjNKNk00QWtrCnA1cFVSZDJka1hEWERhNlNmMmFo
            MENRbmhUMnFyck11RUNrdjA3eE1nbm8KLS0tIHFxL1N6U25mLzBIRGVBY1NQVjBk
            WFBaTzJ5bGpoUEtGUTlqZnpTYlRiUlkKaYjLdTNYlYIoC9a80NBH5OtICZiXMX12
            SqYc8Ol8mAOoPAjqp5n/ro6P9hVl+3xr0wAm3BYWpbpdnLiAtAiOUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T08:23:59Z"
    mac: ENC[AES256_GCM,data:7p1iUumKquicmJD8pokWQB8JITNLxxTM2KiQp2XlDutVVtBFWGun9zi26Jc8TTVwcmBx7dHiAWYDIC2oBz9nEneovVMbaWRuzypBE2y9aTnFt+/R9s+0sQVEs8t0P7dfbGoph+5DJfexiPcb2JN7noqgJdGlPEK7Fq/svd4S9wk=,iv:QNo1XlbG4fog7LdrPOfTd1wMyEXYgYxeQju/O3OUosU=,tag:9sshqg521ZquxVS0ciIOZg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
