apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:FJm86ZBQ+TsXtUPaAjAxW2Wel+t/onukEiIx6koWbfUq0goKJL9qAw==,iv:KeG2N8qI6kyg40uTJMjmkcdJpCapIBu5BXSyQGUOACI=,tag:MVwLH4/H/yjhxT6dRK5Mug==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SXM0RmhxNDcyY3FsZDhs
            bk5PNzNQaEcwZnJucEJzSWEwZUZwamNqWFFjCktjb3ZXcm1TYVB6WStWMTJPSUVJ
            eWRVMkV2eHo4OFBObWR2cVVnaE4zQVUKLS0tIGhqbFB3ZVJ1RlUwVkxLL21qSnMy
            aEF0VG5hWEtSOFp2OVVuMmRINWhFRGsKqcOQhlMtZJIgX/gsTXI9Qg9V1z0eZ5gh
            VxZqAFQFB+uuvl4MV66oHUPQuQ8SI7higsASyuod5jQlhdphGf0YEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T14:23:43Z"
    mac: ENC[AES256_GCM,data:6xu2AyeBXmoJORGMrYev41yfq6l0tWPzSIM2UgsJBX9t/08g+8KkM2QiDTzYH0Ox5UzisHjZnOaqJsOxh+UAP9wBeEMZMb4Is+7VGrTR+snduUmm49J6IpoqqmrQ98gQCnbkxS4sD3ReG7VjfeG9pFI+EChbpsDrJOioJ4fzNBg=,iv:xdQDMl239J/eilGrGqgP2E9RRXIBoRKzXRyipmVFlSE=,tag:m8xCk0KmWouHka67/kQwlg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
