apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:YyWOfRH2ha+voHsa69e3zj4cxNN9Y4xhl3MT0GvkWFpASeEsWh+Tgw==,iv:rwAKqnlIYk93uFHYV5kPXiZ12b9lzD2icUp1BReI6/A=,tag:Q0lm6fUmfouly8cJw08Esg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT2k1bDNiRkNnNzlkRHVa
            eUx0ajRNR0UyWG0vM01aNEQrb0Q0a2V6VkRnCnpUVHZQTis4elhtMmczUHk2Zll5
            Y0xjL3FoZGw4b3p5bTlwRkhyMm4zbXMKLS0tIEhmYmt5aTN5Z0Zod0N0bmUyZVk3
            UENwa2doWlhaM3BncEI2QlJLRFBQbjgKU/B8xmVvHdrAkI/qdKIU96iYg6dKLxpd
            mqlfh/ra/o+69ENACg0gIG/hdX4XGSfAMSAvx5wI85vvttN0xz5VOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-15T20:21:09Z"
    mac: ENC[AES256_GCM,data:1SlcPSXMJV8pxWKAu/2AHRA5rm6TbbIxhXA0/7AK66jRnSm1Mp8xrd5nxMpOK5r5hk1GzLyJdYr3/scTu9PSH7czUdaJYcLjg3FS4xyL2H2Cq0ih2M2rzn6k1QB9Tj+oabwDhy4+jXci9Z+EORY6PG+Z+H/yqMyFMzqbCabxSGw=,iv:FU6TKktqOIUjfpiy3X6GwgvhN8gbqa9boTdcgIHarks=,tag:kKY6dUXArgnI/Wcmb2q0Kw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
