apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:e46UaAIjJyCyF3twrNHHhfW43f7MHWBYKWWIgkUBPjlYiKzZyZi7+g==,iv:2yRIVrgYTb6cyVLqkPc7jdpVjmJjYVEjA+DbSRi7iPQ=,tag:19xnbX4xW+aV7DwQkMDgaA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OXZIRmV2UklOMk5LeWlC
            WWZIaFMyZEdNNXdqU0F4dFZHNnRXZUpwcVIwCjNGYSs1YjlrZWo5cklpaFRiK0RP
            bEtPcktZOXJKMFgwcUg4Q0psTlpKaTAKLS0tIERnZ2FFaUVVVC9McWppMnlnWVNY
            eEQxN28yZ0ZLNm5OQ3ZpMFRJUWY5QVUKTDmdgJv2UhK70REW2aFOpWydlrRbwU/z
            FrNnjifEA7p6h70s1KtMBgF87KKDTl4q6zGLYZl207SAaKM4VNB2sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T15:15:16Z"
    mac: ENC[AES256_GCM,data:aJCw9beyyr8njgunNxLm0SoYA4TH8oFL7aaVRZbsyP6MrCtp/ZwG6NRtw1OzHifk4zIZ81wysmYEQVj3ggVaFurUK7QVRDXSzjnNW4PUTcTiEPzn5CQ73Bz31Pj4QfGkI4SjNa92x7UVqMaCnHKxFiA5GalaVxVjd7CdxjB3gJ8=,iv:feUVa+7uCGUNm0NPPbvG19GD0or8cy5dG+Pp1oaURIs=,tag:Gmr9DJNjma26CUMdxj+HQQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
