apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:t99u+lZXcrygOLof2hWHfarqhSyatQcFEzvQxsckpQucIWoK3IO99g==,iv:yR2cKpnzJ64rqib4KQuancip7Liv67iRqya1P482wpA=,tag:Pv/T07sXSIC+oaOUUQbW4Q==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcHZkKzhESmVTTlYzazJ0
            L25PVWJIWkFKVUZHS3pSbFNWZmFDdHRWSVZBCnRrRE1jNXNOaGVybmNlVDFkVDRE
            ZVlFMitKbmMzbnRVazVoNHFwMVd5bTAKLS0tIEdtYldyWTU1eWpqT2phaFA4bGxn
            KzJ2TTNqTnB2Tk05ZlRUVVdQRno2eXMKFGvQOYniO/u0SNQJEuAhAJIPKN3ydMxr
            0ykXxZCrk18ZlHAoJOBUUb9RSK2rW/SPbfVIMvmSl+ZkuAzP+cDN9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-25T12:19:44Z"
    mac: ENC[AES256_GCM,data:qPj76Z1ou1954rkZaEfXNMSZAKbHy95Wa/YNk8TMW0cjxjM/THWSA96TfxoyYus29CrYD0i5X5qnB37di3bbJxzlZMA+oyPAHjYptBy5jD3fzPZshd/8CWbsHre1dHBOXfL5umsm3kr/Gz0EFxhmxyNElQVaLhuNmRfgN61QBKc=,iv:szssjl6xu3adwLoHunsMHNps3iJJGDuNdDses2nvUNc=,tag:uBRH2sCNUEzH/lY2cUKdKA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
