apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:x3LqAh4lPrRcRZrFtWnhNbMSF70Kpo9j2YvFlJQonjT6r+g+f1kqHQ==,iv:Xig3nw6vvPp1aWkhEgoayJdy2cwqjDcM5WG/m1x34h4=,tag:M8nOVdtd4hZ2XRCyJVC3ZA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYklPWUlCYXZ4Vnc5bmpI
            VndCdTlCak1Qc1BoN0gzOHM5dzNZRVhSNW40ClZWYjdiREwrMkpHS2JxNW80MXEz
            STYvelBLUy9hQktMSks1WXU4dlVuN3cKLS0tIERRd2NDNHlTYXdyRzRDUlh3S0ZT
            YWhsMDVwYUE3bzlTVDJ0RUZhYnJxNWsKOy581Diw63TeDqr/DRUu9fAODiDsBvkU
            MpCcsMftTupEgSgaKcsjoczATbQM3W2Ic6Gxuyhwcv29NuePcD2aQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T22:20:45Z"
    mac: ENC[AES256_GCM,data:KIXHYx/2riTfD3OOI0+6QLjhaCiY36Vu4Rl6XsdwT1bRfl950z3jswR7IU9O7AYdcx8tY/C4Wz2SoyKet186x6kWq45Oz3RH+Tn5v+8Sz8AvJ2M4YtKHAD4OPY9XbJy8B2bToFCFC2qCwfSUX7N6sONlcfTMtROEQTh7hpRfx3s=,iv:VqrQFPOZCs9EMLa5G9LdJyusvAKoGmc2IjRwZBbLpw4=,tag:JFxa6rlZnE1GXC7jnYTh2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
