---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: comfyui
  namespace: comfyui
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 14.5.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    image:
      repository: lecode-official/comfyui-docker
      pullPolicy: IfNotPresent
      tag: latest
    securityContext:
      container:
        privileged: true
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    service:
      main:
        ports:
          main:
            port: 8188
    workload:
      main:
        podSpec:
          containers:
            main:
              resources:
                limits:
                  cpu: 10000m
                  memory: 16Gi
                  nvidia.com/gpu: 1
          runtimeClassName: nvidia
    ingress:
      main:
        enabled: true
        ingressClassName: "internal" # "internal" 
        hosts:
          - host: comfyui.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    persistence:
      models:
        enabled: true
        mountPath: /opt/comfyui/models
    cnpg:
      main:
        enabled: false
