---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sd-webui
  namespace: sd-webui
spec:
  interval: 15m
  chart:
    spec:
      chart: sd-webui
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    securityContext:
      container:
        privileged: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "sd.${DOMAIN_0}"
            paths:
            - path: "/"
              pathType: "Prefix" 
        integrations:
          traefik:
            enabled: false
            #auth
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    workload:
      main:
        podSpec:
          containers:
            main:
              resources:
                limits:
                  cpu: 8000m
                  memory: 8Gi
                  nvidia.com/gpu: 1
          runtimeClassName: "nvidia"
