apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:1vVa4Hw1sXhNRaQk,iv:o3gxY6mO0cD1oFiHwBJO1jxhISxGLzI2J9kHJDv//OY=,tag:YKhfqQQ8UIluS91TRooGZg==,type:comment]
    PROXMOX_IP: ENC[AES256_GCM,data:WOBHE52k2HVo80w=,iv:VdUUhMMLXQnyUqjNrXTbRsgKyIq9YV1t0zqBZdyM+6M=,tag:sCBrImJx7NnkmD1t++8y8w==,type:str]
    VIP: ENC[AES256_GCM,data:N3qM0sLL3nU0X5o=,iv:+TUSHr5gGBQycSzwEG3J0u5nBGHPNfcIdXzX7pARDG8=,tag:VyROuc8+F1+kT3z/kTEO8A==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:NzqguzJD+p+agR0=,iv:fyjyXGIHQAYh/fDhpD8c6DRj6SRVQYqJt+H1NwGqgM8=,tag:QVlosOG7h4wnc14dzomaSw==,type:str]
    GATEWAY: ENC[AES256_GCM,data:TbB8hvYj5z+eFw==,iv:5lNlxsRR0V63FvqMB491x3kgSXFXRD45EOL1iASiQkg=,tag:d/pgZj7BciWCv0legMibpQ==,type:str]
    #ENC[AES256_GCM,data:gHoS8YLTcSs8nGuRGEvo,iv:VEvd7DgCrNu+190AYkx+PwBVO+jwCgVbNsR6SHxheT4=,tag:cv2ZzsVbT4mTogI8TipAhA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:gh4PHae9Cw0ikbnW1MzxWdAbDqbALgvlHQ==,iv:i33tZyw8xJDVu4gSQGEBKiSqug1c7eIw+1ZUgh3zprA=,tag:3e6aEaoPkJK5uzY+mCGD8g==,type:str]
    #ENC[AES256_GCM,data:OSYkBEgDBCliGxq5KGqiJcWKQ4GB2ZlwBA==,iv:wnNji8NMYdYk5W+IehGyy5MeoUY9atFkgeYZtajrfGE=,tag:ztZqYI0hvoXuMVA/5S1Itg==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:MIyMAcm9Epfs54bz,iv:ajDVNqGDAShq92xGk1vTsxt7Goeq/qzH56WGzLDGcCM=,tag:kMgoqZDsy1JblOGM/HfbSg==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:FtujCf6hVdS9OP7D,iv:IMcEk+a2srvY5UaZDkP5gLWRz9nrXOQDgmw8pM6L698=,tag:n1f3IAPsruhp9UXcCJfrqg==,type:str]
    IP_WHITELIST: ENC[AES256_GCM,data:Uf0diK3zKDPgNqogwB3LDKIIE254MfZPnWc=,iv:D2In6sJH7TFkHw/FjGh+ngKa3hdA/JLtvoM1Nw3SSko=,tag:Q8qVOdelrYO0BrwXrrYkkQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:osERl5MIGZbU1YOR,iv:+A4+woWe48mR/odPddByBpwk5+I28g7OpIM5Zk2SfQ4=,tag:65/8yQT6cgR49qGzK2Q+pw==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:BPAUGHBddQkTDlij,iv:z2JAAb5lgldxXnS/X1wyN6noKQxQStZq5TZFjz4tS9Q=,tag:BeVwGAnrt3DX4hr2m+rk7Q==,type:str]
    WG_EASY_IP: ENC[AES256_GCM,data:ZcgHXcCWLnWdNrwI,iv:TlwpyXigTft8SSvyZVLcHDYLg8in9+ZSMtLsqta/Z3w=,tag:HrklvjPKVFWP3Js1Lg81uA==,type:str]
    #ENC[AES256_GCM,data:EJCBMXtGnxSwkmInqb5SuLDV,iv:+USgepGuH1z/o+JQ+iWSkiJ0j2FdJAiggjK1eqCXr4Y=,tag:qqbRGr5xxPENMrQ+MmEd1w==,type:comment]
    BOREALIS_IP: ENC[AES256_GCM,data:nShHdTiyQEDBIbQ=,iv:Pe6bWDt1NWaqog1rm35fXuTaHT0Iw6kiDydGt2sSTIc=,tag:ExJJ+Q6rWTeybbGzxG+o7Q==,type:str]
    #ENC[AES256_GCM,data:N2P+45xzK+6It9X03SYYGw==,iv:uWSKUnHFvwuiFxRgJQ85yD/u4yT7UI3Wxdy+we7Ky6Y=,tag:bDJXHnoPpurLiUsJU7dLqA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:qnhYlXuSEZJbU21l8g==,iv:N01WzfQ3RWDQ/+J6G42h5RENpS/Mb5yoP2CZwumIQcU=,tag:29wYGdFkZ5qrRL1ahOR3/A==,type:str]
    DDNS_URL: ENC[AES256_GCM,data:7Hf+J5qvXCPeNeaVqZSvwqLVrIU=,iv:SiOCPXy6nr/dEKMQgSuV+g8Ab8PXY5eQpwVUKFHgLnw=,tag:vcCICASMoGX02aro8AIIdQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:y47VFUq7kP5bGkSHGly0L7S01A==,iv:o+cKeZb5p7eBPFWHC2rBvJsbaRl4ebQPV/AYZ1x5tBo=,tag:WL9WMuiJe3yzUaQXoLbCDw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:JNnaJzNGBHSAVYmL3PWhthoUTp7KG+KnBDlSlEGZq3pgdB/W7lcryQ==,iv:SzHD1NtDoSQBVMqT5WV/Fc1u3zKSxuSLHRZShfAAaQM=,tag:PEkMmNOCjsrMVIuwS2qj4Q==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:7Zs9dWcErFaw3eUf2NSMsrKaJIrOaYNkmvi8HdklKmY=,iv:W4aghQZMSR1E/v2kWOMgsytrqVhbxPmCAOGG5tKmwe0=,tag:5myROzCuRoRtOhT9Gf0vSw==,type:str]
    #ENC[AES256_GCM,data:sNOVbRvOrOwAig==,iv:Q7OkRe1WK+0F6ShzQx4UHSyyEetshcoycH7MedPin10=,tag:rzmsLgpZZFAM3vfnSuA8yw==,type:comment]
    NEXTCLOUD_USER: ENC[AES256_GCM,data:5R5pyOIQgk9k,iv:z9Z5eN5oyg19xtB1KYIUgtOkxrCXWwUvEm51MNmKHKY=,tag:7gJVTAWPix3q6XyGr5lwZQ==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:fWdIufetMjtzuOiihwRDcpSfcPE=,iv:Pwk5qnepB8KKdUe2c7AEdu7hYGP/rQTk6iODlXQ0iD8=,tag:VtkoUitc3OITgYpF2Zdcxw==,type:str]
    NEXTCLOUD_NFS_PATH: ENC[AES256_GCM,data:BlWWEdpJTcAaS8l6anl7P1ga+Wf6AKPD,iv:wzJZWBJHCE23uZGgVUI2KEuQsanL9A1eAqEu/VCuzK0=,tag:Y0Y/X8Dw9NbTBCFc3d8bCw==,type:str]
    #ENC[AES256_GCM,data:XBSiutKPdvh+l0cXmNb+UcQ=,iv:8buqPX84HaxTmVd4Dff9cw3GkXpx3Od9LVYlYgCNc4E=,tag:3DHconVrqZr85ptBN2uW+w==,type:comment]
    METUBE_NFS_PATH: ENC[AES256_GCM,data:5Is5CLNuHcpsfrd3cvenQpPkSRuU2Idnx1k=,iv:WBy0qJ9aOwZ6Gkzj2oCAe+2SaagS1qRDXR32VBeig3I=,tag:XfL3suYVucE64UTIFXsGEA==,type:str]
    VIMINARIACOM_NFS_PATH: ENC[AES256_GCM,data:L5InEZmS8pejv+Zq5nUuPj90sLu/9ZpcLtR1X9gCZUJZhmuazEtj,iv:KXAG+Ogjy6UNjj0mxrH6xjzGyrjeDmjkryqfGeGNbTc=,tag:ZDMGkWjcA9pIOUOPj+cVvA==,type:str]
    OZRATES_NFS_PATH: ENC[AES256_GCM,data:QcN8wlD0BrlLzLlwaGRdrKeMwXOupspqEXNn6aM=,iv:0pNA6XKnk6ev8EBXydnjile7fL1214hl2WGbhBDqgpo=,tag:16ebDqCWpmlOtCotB+V+5g==,type:str]
    #ENC[AES256_GCM,data:1pKnWDvuVHe04MeCs19tA/8rXqa5z8twqCMl9LE5e7/Ymfw7MyoVGjHjfjrKc4OkO37BLnfgT2I=,iv:QUMpFMcnlJJ26GY71KLujl5rqN2F0tdzwpnUpIw2bGs=,tag:eVwGQI/PjEfvWQZZKiFcHQ==,type:comment]
    #ENC[AES256_GCM,data:TKMRZrX88myMMMJ2GEG6rcG12d2QzY3BWA==,iv:rPdI94I8O8PQNAHcdYsefhF0GoYcaEqF5N6gNN9yAwY=,tag:0VciaEWmCNuRxSVEOpA8lA==,type:comment]
    #ENC[AES256_GCM,data:lapXCyAcRXTtRzuZxF0M0jvVjXJ3D/fDUUVpv6zZ4O32yMt+dFziQGmM+BFbwfGB7/pGwRcXSMACWL4Gtk9wqMHKiFCPyoijDhELp/A=,iv:9osZNG+qaGdMxXSNWcC59vd8VXujsyWTcdzURpeviMw=,tag:z9LiWw2X9+DCig5gZsZLaw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:psjXmJpD+jA1cPtwKe8R6bc+7rJgGR2UAPbHR/xHFpIpWVbK,iv:bD6v+mtZkFR+S/kuOnIjyvowKfkXJX9vBpLQ7Pt6Xj4=,tag:RiehjSGtbRRGAZzU1lFhvg==,type:str]
    #ENC[AES256_GCM,data:fmZcNkLTNKHZhqk6VxreUKSNt9t9UMEcuLE4u4EFxG/7rTEVwP0UhAe2by3NVSDIZkqayKf7Ff1Mgow91auymTExz4omCqI=,iv:t42CCPfkrAWNW/LEy98MZ8ryMYgegF5Yknohzq5Y5Vc=,tag:YjNe2C1lzKJxqs8fNmCjDg==,type:comment]
    #ENC[AES256_GCM,data:5/qgloyphGeEY1gKfOky5GuDrV+0kt63MQNnV49djQm5TTgrgCulzY1Mff4PCDeVJ4whC1lj,iv:IHqll2kwmrI53SisStxpaViyYhG2PnplNfxAm/mug/c=,tag:8YuloAvHwDXsOSpCLn5lAQ==,type:comment]
    #ENC[AES256_GCM,data:vWWTmKTCmuMinRqHtnoKhWBkWMmRPfBI6MIKVzuAJfKJHqs=,iv:SOuYlVz0CElqQaqhKvwS8W+zJtnqGRm086Sh0k/vdwQ=,tag:DzcCr9j1vhR2RqhMTLX+Nw==,type:comment]
    #ENC[AES256_GCM,data:xYcN1GqZAfArnQYFcpF6kuvYAh+6aqxEux+5uHKshMQZuoeA3WpK,iv:ToUeNvRSxhaj0/fJlGA7LXxjkcQpwjr5ouhaVqcXXnM=,tag:Q3nMP0/ISg6HbgeDa4zYeA==,type:comment]
    #ENC[AES256_GCM,data:63ITwRXLEFKSHfXmHlY=,iv:vic4g8aOZRNO5VyuebpQcriXQP68IgvzOsu3+ItagqY=,tag:+fQOqlZGaWLEDwXEB8ptHg==,type:comment]
    PODNET: ENC[AES256_GCM,data:dqVZr+wz4+zgmnR9zw==,iv:uIi2Il9JjNGkcRBcTJQL5rQ26W+r/SUzcZhoEegnZbQ=,tag:u9N9C3G2OfMyQWvhkNAqiQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:huGbMCaB4Lwq5Lu21A==,iv:bdx00fheZ+HdbMa4/5CoLV5Fs4+zbl5sOk7s8p/hbq0=,tag:fZNQjnEHQXJyPNxbdc33dw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:8wbd5g==,iv:/B4nOYbs08fmqjMMco4xfWK1t/ZE5QrVtQX+gVeEMNg=,tag:q5PByunRdZShWWvrjhA8Vg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZCtIejVsZEhZdW42SVB4
            QkdTdGozdEVsVWxvZW9NWkZ6d29mQVNpV0NVCkFNeU9XOGF1K1pwZ3RKVHBMQm1m
            YnpJRWlucnQ0eEdmQnpWNlQxR3F3c3MKLS0tIDNzNUZOeWhaUXRJQ1FxNGV6NTEz
            YXZrWUdBSXM4THM2NzdMWFpveGhjcDQKLL044Yn7aREpOrIXBcuttVfbGuJXeugf
            o0zKatlGb69pFm8tWG54SLqLEDswILQaLRRd2y7UloEyjXjVZHioOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-07T06:56:30Z"
    mac: ENC[AES256_GCM,data:5FIzc4NML9bIrJ5s8DuHlkQhPQ+sc+ycba6ILR/vhWOGZpIJ0bMsp+eYsF189hnqK3cXIwHykBnCDU3QGTFfdptk8JtXb8ojsC0sgd55xfvsTMeRkCzJWZ2Ru2LlWDvaQg7eqWF/0o58EOCsXLqBBJRraat5EoQI3IlDz01IfDM=,iv:HAeNKnyk2pxaGUBinzYBTWGh91BMG+Yo0XzUebve5Rs=,tag:W9yFqDtDXWmHtW+UC+TFyA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
