apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:YCQ7DqrhMxQtfKAN,iv:hT9rz24dCiBmtWqNxK3jZj5HQpNMQ4hO414JKCIs+rs=,tag:1I9ucTMU7a/ar6KK5vqkZQ==,type:comment]
    PROXMOX_IP: ENC[AES256_GCM,data:6ZwxjJ/JErwz3m0=,iv:5m3QbioE7sITcVjcsIeZ3iv3YL4Y0SuKDY75oQEl+fc=,tag:wprO2EG+oTJ+PyxUD5gRhA==,type:str]
    VIP: ENC[AES256_GCM,data:yT0yFub1leg5bkc=,iv:kfj7l7IbWnrRJExgmuhbozLpWztTXleEH9f0TysWRdA=,tag:Gmgo66gfZMPd4QrySWlC1g==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:bQiSoUaaIyLB0+0=,iv:STHjcQn8aCP4rKZ09Iyp9H5Cht7ShBfpXPSHTo1Bxmo=,tag:SeaXKnbQxz5PzVo5jXim0g==,type:str]
    GATEWAY: ENC[AES256_GCM,data:JHojAImoeJVtCQ==,iv:kv0zRdGrKg/peUpLNgAh6Hn2HSwa1tWS6hU7NG/qvfw=,tag:VdidMoitcpc/WE+hDtj7Yw==,type:str]
    #ENC[AES256_GCM,data:C0Z0sebZ+BlxCLKjm7cR,iv:bWrCYQkpfzVuq8Ha8J7OZ/TBp7WEeyUHvVCWH7F/VOU=,tag:nVWXc9hXBkaHHxZseKNwtw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:yGhad9x9fNnckwNphQ8y/+Syq4eStfMc9Q==,iv:S3uBwdyBgvZEOkd16fPT8K4hW/1FAat8k+2AMNDpTrA=,tag:mhsZf/utSaB/3uadeAga8w==,type:str]
    #ENC[AES256_GCM,data:/XB2MYqpJdQ0LPIjKi5K1LMu9tQhI3A7xQ==,iv:CVls6Aknjvw1UxUUB5thELGCjsC2LXB+52AbClfszuo=,tag:PcEnpcdfBzHrsfXxSXIKgQ==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:zbZ816sYP1zf/5N7,iv:JOh2MeQUip56Uz5xnHaRk9/ObfQS82cv7xeM0QtTAPs=,tag:q56OJVYwBTzjCx93IRNjAA==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:3ntb0qqe/qwm1AID,iv:RvvWtpdQXtfhaq51Ie6JXPwPPfSu0I0CiKfNC9giV+Q=,tag:uSTBDOURiZPMpDEr0nF3vQ==,type:str]
    IP_WHITELIST: ENC[AES256_GCM,data:ZB8Mu6Gi6is1lWwiw+HwAITb+b0mFaPWk1o=,iv:YiFzbzaqbqOfIb5xniA07lomp55DYIumWoBtGNccOxw=,tag:3d2/H9wNkatTrM7By1eLqw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:mz/oXCiy1Wpxiy6+,iv:71iNRPe9NuxlQtMXJNrGuqjlChd09Od2XnrOg+5Ecik=,tag:doNmx/TZngHAUn4WrbRK7A==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:VM52bNYg3R0jIZLn,iv:n9mFmktzL8zAc/kqXLaIZ2P8KZsXN1CHvu3fRiI95/o=,tag:oQ1b4CfTHHtKwSkus9EeTg==,type:str]
    WG_EASY_IP: ENC[AES256_GCM,data:v4nr2U51Us9O7Mk1,iv:zC1w9b/FSHKecF72cuYgAnLXt/Vu/gpdO8JlzWt5344=,tag:uRHpKtMOgZXzdEwrMzAFZA==,type:str]
    #ENC[AES256_GCM,data:CAKhf0nOkRS4I8/EpNHIv1zb,iv:BAjHEb84Fg2IrSsWkU6s79RjlbFYnHPmL/NdwR4VZcw=,tag:Qi5FpTbiAlpZfhCY0sHSbg==,type:comment]
    BOREALIS_IP: ENC[AES256_GCM,data:wbDYxWBXeFuQ5H0=,iv:yMtX3F5NsCfomhkGFaFVZ1/++gsINbwXyWvv+pnkduA=,tag:wsMhDS7qW5mMnWVV0fwoCQ==,type:str]
    #ENC[AES256_GCM,data:ZP5Op3MT/ZZ/FG/GUDzGmQ==,iv:OCGUUxp2PA0cmmUh0gd4pqPPrfuOan4k1EiLcAtY5HU=,tag:7lqfUvNKvIr+wZeuTDjP5g==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:b5Uvmb9xkPyZ5AL9mw==,iv:Cj/Lg2FiLynLNK8LopVPo1+N4x6jWVxw5LGqoy/kcLk=,tag:StOJuGJ5vWvlBuVjn0MHug==,type:str]
    DDNS_URL: ENC[AES256_GCM,data:c/dfXMW5vdvSSr2S5GHJXmZg11E=,iv:EDacddD+NfunImOLE1E5WVMQd4ZA15eownawdN4xMEk=,tag:S4dQ1dWJjqI67IYt0LtDmQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:fMYKBQ2uSuf2XjACIsfWsmyM0g==,iv:ER+NpsvrLFQ+JYRbIFe6dmqe00cQYhAv0yQeyDhgKc8=,tag:1NUh/mWPDS4MDGwnsg3AWA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ij75DU4tsqSQ+Audbv7Qz+faPFVO66EWKkRXnMDmE2jwdEjfooOpsA==,iv:FreZ38MXx5TIRNbfbylOu1UL5eGVre6gNaMWjvpLJS0=,tag:eK9ZzAKIxEdOE7z65kdaPQ==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:NKo6bA3tm3nddCxHTM6AT1JGBVPKPeXEyq7LMD3KBCY=,iv:3qdtyH5j9rLF3cWl1bLIMJ6E/VJ3QVwAKbxSg90VTLE=,tag:AjU4oTcH9MBIWlFKrRxd7A==,type:str]
    #ENC[AES256_GCM,data:Sq8nvJFUL19KJQ==,iv:3QFXKGDg+1rnwkSZHB/NoFzJi/bKTGX40Pb49eMDNKA=,tag:9uNjhJrx93iZ5s6jQ7mYWw==,type:comment]
    NEXTCLOUD_USER: ENC[AES256_GCM,data:xCy5cU36JNeS,iv:3vRL/TbFkGQ1qc1R6DniBO0DyuM83aQxO/m9RMkrP5M=,tag:gJg7o6GjXjZBRhZlNyw+xw==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:l+vejzocC4WWDUnPEai24+7qYyY=,iv:PkAAXUwiCfRETcXuGsVkIBUZnUAcD5D2Nc/2ArR59tk=,tag:TRckbhHK2pRy1LiK4RksRQ==,type:str]
    NEXTCLOUD_NFS_PATH: ENC[AES256_GCM,data:QGIBKJRHLxLo9fW2r7ViI2hGkRTCe3Ez,iv:eHF9Q3RCAwAbIZIVGpC5DvGjrprk8tjzkyvdHMP34lc=,tag:9fPbte+VCdDlvvLPNwYv+A==,type:str]
    #ENC[AES256_GCM,data:6tpoi63DEvayvoTEcc3/8X8=,iv:rWSN9ilsKNvIviZbbuvZ/w/rCm2GJyZdyG8qzmVjFmY=,tag:OIOyReAGkFnNOTUsroEI2w==,type:comment]
    METUBE_NFS_PATH: ENC[AES256_GCM,data:V6AkO5O3uXUh5rwVNuBcTpOUr1YcVUDU2QI=,iv:eJ4VzTHyqPvqdb3Y9h78l543iYwSlSfYggnUg4AECpE=,tag:8DBKKLgYdFqjO3VROFZ1JQ==,type:str]
    VIMINARIACOM_NFS_PATH: ENC[AES256_GCM,data:k89nNwPx7a/QcSBS6MNwS2nBu0WK2JZfXasZYTwuh/pkARYuv3YB,iv:Ohlk3v8ou6OGBOmzzDKxYGz5uVEdhRdUM/UPmpPR4EQ=,tag:LygdnXkW+6+vcLBfsYO/DQ==,type:str]
    OZRATES_NFS_PATH: ENC[AES256_GCM,data:59w594JbKr0NHXIesEsBo3h5bpYRneCvZvk49ns=,iv:HTnZmL78rfH1/tQBfgIxa2vJaJVkUZTrzXni2XjFMxg=,tag:CkgvZ6pQNRcZBkEx8AxNQA==,type:str]
    #ENC[AES256_GCM,data:P4zr0OcxCfD82/yNFyMa7aHU+kYQS4/dwVJEMrypJuO8ZUbofU3ofvV1mE83dRKJde8p+swidFA=,iv:5JcxLolCzpaj3sENO0HTVwCxt7QtQy/w+mcG5ZHQnnk=,tag:LY510+FKRZvJH9ANmQEX4w==,type:comment]
    #ENC[AES256_GCM,data:ny2Y57cRPC7bJJJ/XQ4svS0AixpNAkBqUg==,iv:kIWCE4r+2LgZAHqVJY6YHI54YAaiXSj7smun1IbKR5A=,tag:nERsKaFmVUDcXjrdm/AvSQ==,type:comment]
    #ENC[AES256_GCM,data:C1m2djGrme3AXME4ONop+AieQli0ppkum6Ir7RVJoExhuh20/BAfln+U2dyz5TzUJN4kMRMtsp0yetzzfmN9td61QPmli+8Mq+iOEuQ=,iv:VYEYwjS2YUWmilpfblMhnsY/A22LcuMk5JpftMtkR7Q=,tag:9DQNSXy2tTRZYQxX2AquxQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:wHxQsu0III7z6QOSUnsSkJDJyQ72ShTcrwjBBB5GJuvku9xg,iv:twORllSAvLs4JVJmSobpp/8n9kZnrLXVRvRB8gkPpas=,tag:Wv/u8eYZxXkz1ysN0aUbgw==,type:str]
    #ENC[AES256_GCM,data:Xng7ajaygK2yOTZXzfApukBY0j+NYSz6oxEDm0B0wxWYaT0pwZ18XyFN54McsOFLrxmkzr5TRh7mH9MU3fmP5X75qglcXaM=,iv:G73JfGEFJsJdG1u6NCM7DuMxR/476ILWM17YolIs41g=,tag:V0Y39KySUZs2bRb7ojd2xw==,type:comment]
    #ENC[AES256_GCM,data:jkjXw+Ci+RzkkzxNpZUQ3ZskLEsGHt5BJTQQ8O9lw9WW+lUlVvfhV0S+odn0fdkdtKFEIhay,iv:u/0598U/+c9sVBt1vcW2mEETMDFHr7igychvDWf42mM=,tag:+ryCJRcmgiCJqxoXwb0RfA==,type:comment]
    #ENC[AES256_GCM,data:9jFiaJY3Mr8Dv4jNt9UGcym+JI+MF+60kFW6ym8DK8sVXPM=,iv:kNDz4Q1yT3y7JyUHENbew665kg5qNQuJ6LfQ23dZ7cw=,tag:3TD7OkHPS0cYQ/4KNJryRg==,type:comment]
    #ENC[AES256_GCM,data:Z/p+peMltPw7No6fdtGAGybl2znqELxxA3mJBIyOvPTdp62pH365,iv:TP630uBGpn7huaccRiCYA4Pk3Dv2XEH0R5ZQC6PVCN4=,tag:W1TWMBzy5st/P1z0a9Nvbw==,type:comment]
    #ENC[AES256_GCM,data:B7iQpvV4ZNiGVYIloqc=,iv:d+Hu7IIGlmmUSdQf3ys3t4Rrjo/2D6eTuFjafBa0QaE=,tag:o0mwH+syRC7UITyv0rzRcA==,type:comment]
    PODNET: ENC[AES256_GCM,data:N2P40RoYFGNiYAgTRA==,iv:VPf5emQcO1kNtkWjf7xh2cceiCdMW+I++6pm7aCxT/E=,tag:nzAxw47O5bNk2Ozh8N/8SA==,type:str]
    SVCNET: ENC[AES256_GCM,data:29pmL9sPW6Mv2iPq8A==,iv:AEwuDqTBkEmky/RQDA7V0oy2nCsPmnMnG7aUtnrRJpY=,tag:GkKm/OH3FAPvv5ooT5cQIA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:nYf6oA==,iv:owBPL0/ncbsmGOBxdLg5BxQjmxiWOUMf3f2vOFcxrCo=,tag:gnEudbcIOE3potGNriDTIg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZlZJdmlEU1JQWkQ3MmlC
            ZnN4ZEhDRjNPUkNCZi9YQjUzU0dnQ1lEVkhBCnhHdU1QcTYxQ1hvYzliT1NxSkFH
            cm00RitxcEdwcXRBcnEwZ21XQUo1SVUKLS0tIFJSRUNDdnB0RG5iVFp4WEt0MUYy
            b1UzYllyTDhYUjVBQ3NqdkQ5K2kwUlUKQ6f56KMDAZFZKbNIcajvBMGBPZ8LdfNT
            o3TRyV5uDYw0fR+xtT6gyhIDcG+0cULm1ZAfA2/v3f3nduP2/8YxnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T21:53:43Z"
    mac: ENC[AES256_GCM,data:WSibUFmI6FVuvi4ILEN8veDO+WquTN/XE/yp7G0kJVLuYV/v7V+2e2iwQ1NUSxTVCh6IUE7N1tG2u+/Hu4wT8fhK+oCDetfRx89Whllm8NISxEwW8hwnbMaYkXLulR9WzYRsXNacK6dphu5n/uIiSw4ZmdGHYZTn+U/4IDUymYU=,iv:NZvjffXx/QtgBFL2HBKpKOi69VfLS3QEQ/4oizyewHU=,tag:JVz3a0RcWVAqDuGXT62EUg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
