apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:sO9/HDQ2c+OzoIXg,iv:Zl1dDGlzduemYrt5nUV9DeReUO7Wn8VWwcVvyWm42oQ=,tag:g7s5MfiTMewDIAJfLG2xFQ==,type:comment]
    PROXMOX_IP: ENC[AES256_GCM,data:oySxyOlS44C+kls=,iv:OLNbEyyAhvdHZqGELYwXmBMoHFm3rlhp14QrAu6xGqg=,tag:unvbbLPnkjBgMo/ya4U4WQ==,type:str]
    VIP: ENC[AES256_GCM,data:ZV2PT6xPioRdpk0=,iv:jCGK7EeFY9PTjifFwzN9qRCP2uX4oikXDlIU/VSNd+I=,tag:50qHnysbE7PFHWPkwgP1Gg==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:BcviVpf6gUbRtt0=,iv:M3Igd5/7lAjrDtRFQtDYOylNCPYnY4aUPiJafy1PJRA=,tag:fAaCmKDoOyG5v/U04WTZgQ==,type:str]
    GATEWAY: ENC[AES256_GCM,data:iqtR8rYU9F9JDw==,iv:fjKskifYCT/fBiH5B2OiG+DYTzPLVwRgKi4OK7sArdo=,tag:fLKu98GC8muxwQPBUdy4Ew==,type:str]
    #ENC[AES256_GCM,data:5JeWIyHutqSI0maORbdp,iv:o3nj4lX9F/2sqRjJ7+8/c7rnBTwFsxwKfsqSE1mklTA=,tag:MEWEM7+pT07d06znNhc5iA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:oFMmQCFI7CFhj2SufxWhu5/0uCefmGdGPQ==,iv:+NGELKDe7AJ2jOJkKueP9mROBKhXaXDK8Or4SRHSb0o=,tag:O2FxR6v1yvdwxxQ9apebHA==,type:str]
    #ENC[AES256_GCM,data:LtHt9F1k1CSeQ7sBhV8oBnT5R+nivPIMOw==,iv:R3kNHQTiPdjmzxEuS4203aYGJ5b5ZlvVykbTbU43xo8=,tag:wpoD7fxjXginFQKFwTnNPQ==,type:comment]
    NGINX_INTERNAL_IP: ENC[AES256_GCM,data:UiI9fSHs8T7mQkyD,iv:yqr462JJT6UYaZggpufXs30BQQT4nTZNfdd+v432Bwk=,tag:ZHkF6C+njXYpqUitcwWmeg==,type:str]
    NGINX_EXTERNAL_IP: ENC[AES256_GCM,data:Th5bQU3nSErU3gC5,iv:V4d8D5+P6l83iMrdFRySqMmGj2OY3NEqq3WSoPqcbZs=,tag:8m19a6Gzf+6pRPOmq1kAsA==,type:str]
    IP_WHITELIST: ENC[AES256_GCM,data:r9jvA0/tSSzTgGAtUVedzoqA1yRi88F29Uw=,iv:Q7OpKCs6T7D20paUU8wieHrNxTTn8NMauMnsZYa+CFs=,tag:C6yQekQdIVvsJ343ErON0w==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:Gfko3XskcowuTca9,iv:wH3P6/lccmhaGbYJdd9abQIepDGvWz2EfhT9ty46ydk=,tag:ZGcHgKdvJg0TECy3rWPIzg==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:0CFyzYb7uH3VcjS5,iv:+UQtjxC0+OZMzVMXYWsA/Eanfm2GXrIi3WgkAEijeoU=,tag:vn3u+jxqgSlTkipYgw7jkQ==,type:str]
    WG_EASY_IP: ENC[AES256_GCM,data:bt5z1R64zAjWmaYi,iv:D/SC3InyCDXXaSlaIeBwOEM/JjZs/hAgadtIFFlZAuQ=,tag:8C/ylz6owlZ9WfvUvuRb8Q==,type:str]
    #ENC[AES256_GCM,data:J4SBXJBbAdBCILAB4zM4hluR,iv:epyXOvLmfuPHlNBCtzWuHDNpBVHgqkelrljcHRtJvAU=,tag:4bTNFUrNAzUv9oVh6JaYtQ==,type:comment]
    BOREALIS_IP: ENC[AES256_GCM,data:M56ba4oqCb5I9Io=,iv:osSEGBsKm5Zo9Vlnu/u2bkaQ/C95BnOeB8J5JNZ9eOM=,tag:ume9yODAH+T8Qjke/akzhg==,type:str]
    #ENC[AES256_GCM,data:4Wev/FF9FUP11FQEe7cNdw==,iv:W2WXzlELWcXrbkhZbsAfKVeO9hcNrpIcIjw4i8TBQ1g=,tag:rovxgScxu4Ry6bPOi0zWiA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:HUTbjTXf64A/Ba4RDA==,iv:sKlCsIW+gNsp1SuunGLVVtIrDS4NrmgAtONivlx2aFk=,tag:TAfQ4h8961+I5RWLI6eZ3A==,type:str]
    DDNS_URL: ENC[AES256_GCM,data:q4IpHoNyAzI1ouwZRdfQ/3amsVg=,iv:dUPMSVD+ET1fz5HMbtaqFFS+LbhsIO9C9rksgN4+TN0=,tag:Qx/piBLxZnTGl1ciTMJNPg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:a0J4OwSZxvXeUr7bHMbpjS1/7w==,iv:/i1xf8V55mKoidweJI63Y+UMPBpU6z/2bCBToE5oR/w=,tag:ncpA/QopK5timlGeQVY34w==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:C5kttG06P6vfKPV8vyHsSUXO99AsrGAQ+Ti2KdnvrC8x976ZqKAiZw==,iv:ynIcSJMazQMBT5dNjFMaKSEb0KFaglUxaqY6iLM31J4=,tag:9fS8ICRzPc2quXmtanBuTQ==,type:str]
    ZONE_ID: ENC[AES256_GCM,data:KtLozcHw72+YIiqsu/ajMIl0DacVkcT8YtXSB5mHmPI=,iv:GaPXuTz6xKLn4YhnY3qFXmGs6/Z97enw4w7UJYhqEZY=,tag:tBEi9LQNLSkza7MtFpcSnA==,type:str]
    #ENC[AES256_GCM,data:Yv7iHHpwiisF0g==,iv:PPAWbg8wvLTghyCDZWHPaW1flihMc6iggdj3H07hQrQ=,tag:MdbWyJ0n20t7CgHHMKh3Ow==,type:comment]
    NEXTCLOUD_USER: ENC[AES256_GCM,data:uhc92cQWC6Ps,iv:QxoQv5W/qd9CH1E68okV7QoDx7zCwxds/j32jjrzeto=,tag:pbWZTtu9Y20tDhVEV9spzg==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:j89JSvbbDu/ry4oWJIL3q8oiiKE=,iv:flMZpMLYz4doIkAHoETQybJId1x3+A34FhuFblkO9CA=,tag:LujwTDUqDCJYBSZYJFrq1g==,type:str]
    NEXTCLOUD_NFS_PATH: ENC[AES256_GCM,data:LlGrx54QnB/vx7wgydXmks+3QqK7mDbz,iv:xARMPi6jx8cFqHOdC9tO+kFDK5uZ/JqkS28tvS4sKDE=,tag:vgr31hTRAxIyS2P4s6N2eA==,type:str]
    #ENC[AES256_GCM,data:mnVa7JW7CgomhmPDHupQ4WU=,iv:itOIRNoWQAh7Efz8bpArRZBFbPiuIwWR9impfjm/RGA=,tag:fcnh0NCvb4UUbcFaBtWbHg==,type:comment]
    METUBE_NFS_PATH: ENC[AES256_GCM,data:qQx2ODL0AQVxUGmA8Du5Pnf3JdhPR0AG2uQ=,iv:9wnDZ/Oki1YrEIggQGkZohk4wUZxnkq3y4pL28qtGp8=,tag:+2aLvO3eGejtBBiIaNaW4Q==,type:str]
    VIMINARIACOM_NFS_PATH: ENC[AES256_GCM,data:w4XgbaQlLGpqWYrPiie5Sr0EppsRzqLeCcCUxFr5DpvgsAjfkEbC,iv:2/peXhx6DHpRL4by4E2Vt+onpAd18jqVDUYOgitUiRE=,tag:eKbM0DVOwESnGruu5tU38w==,type:str]
    OZRATES_NFS_PATH: ENC[AES256_GCM,data:lr91ewltFrgjDJ6VmRu960AQaM5PnDM+dUzmYtM=,iv:gYKNqVRg7ZGMu4Fqmwdhtbap3g+OqWO8CZ2iLF3JGzg=,tag:Qh6SwXdjP1odW4zQMCmOVQ==,type:str]
    #ENC[AES256_GCM,data:b45adlDKgXfuEF24pkPDdwG6zGh5JQiL6FyFSyZpS3CcyNq9JWf2qW5PAzZ8zE5RbxIL0bOTIrI=,iv:7wrgu6vZxR1BhcFHBix3RmaSIvq7IdXeQ8ZyR+8dCX8=,tag:nRy11l72f0e891nTafs8Pg==,type:comment]
    #ENC[AES256_GCM,data:Y3Wys9bPFyW19adG5/2nTBTSeLc1C9xlTA==,iv:xKa4vKWP15oS5ylsJoRmeE1hy4P6KocS75fh1QAMa40=,tag:o9IdsA1A+2EZ3xjja5nJpg==,type:comment]
    #ENC[AES256_GCM,data:kjISzTjWX5hBtrWtZVWHUuHepWceiTMqO+qH/rjVRlAjJ1LIr9cXz+Jm7g9iNFOUPfyThoGRKQwNPNFGxjvV2ln7X75bMT/qAeD2XpI=,iv:jiGlGbmfId3+ICqaR2GAxlPbPCZtYACBW41m7nYN+DE=,tag:awBAYCFD4aYQfJiR95YuAQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:2dokFKC827bN9FQYl4hCr6qrxS/ptxk6rFpO59YkgSyVm3Kn,iv:XYXcFU9gsqchW/oyApm1uBsvAvz/1nGDTyUnnTws348=,tag:oUyyDuMxW3/7781HVdbtQA==,type:str]
    #ENC[AES256_GCM,data:CjatyanfiZUgSVc2kNvnJAFYn7sBxjwXpSYFXLXCeZUzFgWKBVw2ZnCyOxnnx26fAYrwyQ5p1PjZYgfD68Exibl2zixq2oc=,iv:4GCTr5hQxrsimyL562B6/gbdlULh+8/qQH7MZVplTkc=,tag:AbBlrf9kTy8a5uXn/zS73w==,type:comment]
    #ENC[AES256_GCM,data:NpZq7kNKd71jY4p9gZQHyEMooyS+wVgPJ+3wSUw1Ro8g4UCD/cmEgK7+miiJ3YORJ7lmLD0B,iv:tKkGHzuUmzayz3QULLI6KCcz69holXxEQN40CZcS8fo=,tag:XhWRHk+Bj/Mpt/9TuEK1ZQ==,type:comment]
    #ENC[AES256_GCM,data:3X4vZHF7HvgCJVFz5TTsz1F5+gOjYklO2KKfikXv6RnqA8E=,iv:mycXIsdxBeKLW/zSlbQtBhjdU0l1p5CpvMuM79CKLoE=,tag:GFNOEnHG0ZDVEcT5sVhkFw==,type:comment]
    #ENC[AES256_GCM,data:okq8kyuwH0JeOdNTbDEOBvn49hq+KAMZPVm/AUBU1V+d8IwEMHMR,iv:yD1Bxuto36OhvtfZunr8rscmfREJgdNMPaTn7sXz1Rk=,tag:86//kM54sY8CyvlUZEBBMg==,type:comment]
    #ENC[AES256_GCM,data:DRgpccxeff0sEZFUTsw=,iv:/8rZNmtHiaoyW9YkywesuP+QzsYgL4o8M8T5eSnBcCM=,tag:eJqiogCoYaqt/K7HUEjeUA==,type:comment]
    PODNET: ENC[AES256_GCM,data:Ft/CCy5ajL+d8FF91g==,iv:VKqardDzEbRvgPJNMwEde6FUhZVMV4BSdeEJSaYac7k=,tag:bPK3htd3li4QGETVBRPWjA==,type:str]
    SVCNET: ENC[AES256_GCM,data:JvChKAlCU4zw07Dqag==,iv:HfZZn2BgzXd0U4pj4d+CuY4MWg4HKq/eoEK5IJ9I6fY=,tag:YCKkqw828VFJHTIlGnFyaQ==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:gBfz/A==,iv:b+ianynd4HjjEmff3G5UiJKbtcls8f9m2ErltZvmy94=,tag:6NziiXtTpNJGl5XHUByfxg==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VmJnbE05WTFPNUVaNUt1
            VDlCMEphNWh3OElmbGoxMFppemtTOWtPd2kwCjN2a2hHdXFNSy8xOVBHTS90bTRr
            cmltRlV0aFl5ZWcyU2I0NzNzcSt2WlkKLS0tIEF2dG8ydXZKNWh0dXZyOVJma3Q3
            dGxoT1FGWDdvc3dFOHJmeGZINXBEZFUKxFJ7P7EKKbroYlzqlEAzeHTeJVi1pSqq
            hcctOK44Cu6de5dXdTdxSfC23/rSsfwJQ1RsKm1FEtMrHPc4Wdg7YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T18:10:17Z"
    mac: ENC[AES256_GCM,data:4YMXPEkbrzHQQ5hL8FJipNjW/mIxulBuGzNiFmBSeprFtTZZFbwIzUQRkTuYCi2q5HAWw/0wgnkyaCHeuoaooSwBJdsjOal4bOMjTTX/sjtnBM7QBWLtJuGXR32OlHJlP0ma0srXNenzFNjlPXcggwMAU/PzP6/jKyHGY+60rKA=,iv:+k6JfLq5KaHhqIx7rc37VK1OZip4Jw9G3W99wjsitkc=,tag:7rGUfzJUVK0pkTSc+j8eIA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
