apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bCoDeIJHaj7NVnYMNGZ0SkUxoCnc3kVk9HpBgQbE3ASEAxmKB2ZoHim/5jZbktDqsEiV0kWDK29Y72A/CXHLpI2mzziZE1sESIUf+DQuoOQ02eOJFQtFJMnvblNc9rBHnQI5h7F8NrWbm/g7I4gWtKRA75kqCrbWMT5MCuC/CEGs8eNvQbnS+GDY1wwxf3ueX3Aa9bekVfdV4FW8xvZ3rU4G2gWxXCWUveVJmtl4DBQk8IC0nYAu3pEZf00eLvPM+aPpN+Bu6tvhJ0qW+1GVPrJxFtC7vIDelkikWpX4v7YcqIkKkpdr6dAjq4Gvw6dyk/SGV2Ij2BBhunO+4+P35fOWDo103wlDfdmR+crm3PEh04wXgvQTZyMDpMc8RxGX,iv:i4d/f5cqnR/7FNh4kZrBA4AItHKBqymFS3bp5apB/OM=,tag:BgYhKf1sN4IHRxifdb0vsA==,type:str]
    identity.pub: ENC[AES256_GCM,data:qfz+Gj50ibEVuHMND7apPtgisWPI4MH76iQ3vlgIG52uYnvaXU55DBrcf7b0YtJ1EZtQKvIbUDr29bpUaYA/iT6g1c1uq2g4roh+EEfWXeqOruHKWKxsoR5wg8kFVNRwQ6p0uaaiqlj2CaCg5MQFdAFe0CpopV/BeO2Ccnhee6ncKtrvLBNtc51DpcNNvxgKs31fF574pI54uHdwlvuzDoZTytS8a512f7n7o7WP0IpUlijKZdNnb949ljsWXttM8vsL1g2aeaP3VJP7gQ==,iv:Wp5gyPvFkAgBdXDKa9s3spTgNS/wRC5QKkeFYcIcXFc=,tag:KplAmWV+IgxKCAT2puRajA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y8iOpI2ohra7kJ+5a3e08CN1/DebTKGr51fN9Nb20jlK2i3gx9G3Fr7x1hXEZVHj+tHMcXMyVPNRVfhtE6P8byrKf6uhztw2JRncd/IjQshDIM1J+NGnPR84GZ9/QFwpinZPtVHZU/1oNUdEFHUDpHThkxMEnI8/nsPZwuTklvaIvIhBDbmeLKuLmYZCQVK5EM8TWHzUo2vF6C8mB0V8nIwgif/aOpF9vi8V,iv:f68rNNpMh+Zsec7IPEpzddUQzEoxFpbWeD9fuukIvek=,tag:v+Rr0uA3EFprOTe+8mTeng==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU1JKMmU0NExuRUYvVFla
            MmZnOGtCVHpnWnQvOXdMSlo4TnVobjBYT3dZCjh2TVpRRDZKK2hPRXJaZTE3R0Vj
            K2V1dkVsWUROR0JOQVZFeEZRU21uaU0KLS0tIHBsWThkTS9naFZXUkYvTnUwbVpi
            NzBLZnlZVFlNSXVnbEFiMy9UUFJqU1UKrrlysODMQFI5VpOl1z3+x0EJeO3DgMwh
            qJkrf/5nfRBZZ11TkCYk3Ip3+xW7nS7TsRX5lXGBZ1wuO5Pwl87UCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-21T06:58:56Z"
    mac: ENC[AES256_GCM,data:sSe0gu0d6CYxXSKw9Cn/V6jMEou7uANrDoX5na/Pvc+0JLiL3D+1QLZ3DK7l4U64K9hsGeqGPY5ras1YAUxAGuouT8om4xTQ8I4zhoDlfW7Chr7QqiogneBSqA+vvUTw5mCHD8ecLH19H34O8mLzoBdtKHrjbETbqQbExl5Jm5Q=,iv:vMOi8p4AAN7YHozENypkPtUPNF+XPePIBciovw22PnQ=,tag:1olCVXKgYISpSBXfKf5eVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
