apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:speYiPRosvTciccntLQKdzR26fScQOz5XEzJmAM/INSBaFichI3vLbhrhznJ0pNOKxlC2sOGF8buGuJwOYZGeElLkwyvnG/HwCqDL5fw1VEwupiBMpansnzuXjqoDMZFdMK6/zyP7QNpXpUQa5eOehggPudBOEA2hmNZbMxOKOb/8Bf2kZuUZyrLfzaZLiAVsVUMNLOGhNeZl4WRU21yIWuRRbKuxhbMMamyh+GW0NXk0n7Sbn0nkq2QnoyOzMlcmXDX0L0YW26aWuuD31vYE6Tb0j1E0KsnE/nF8v/JfdutSvov3lW4Pff+C/+zKGmSlS+20k618s93pVtqvsQCnAU58OOwDteqTV6/l2noe4Z0l1N403xAHBYfPBTv7MRn,iv:FmptGdHqCNAgKZvZ+DQp98AnD7h7ckK0dh8ZCggmhSc=,tag:3cvgLVR/SRLPMWGrTW1pWQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:3lJ0u0EblpjprEprr3uNZUNi05hTr/sBlDdYZLQkQFLParvMyt7GVm+Cp5PuZQ6nllDR0Yq3b4+I+axnn7orqYhRd6u19GzwpYxO2x7y7/80pfLTqTjiTq1SdOtrr1IkWFDv8r3Zcxg9idJYVYx9ZTq2wYtY56uwZF/7YJ8VbYfR5hYy5jHER/CX5xx1MdK3KKVPvv4FdzrM9h0nYJj3cYEOrld5GfaR5jbP1rqK+uxACayG1clorDYk679LsDa9jd8a6YHfZlNmAMSxKA==,iv:3n4DIPiBMUPmameUe5fiKlX0vrUUIlf763w382HFZr0=,tag:+bjuVTgTK40yp3VAGeZ6fw==,type:str]
    known_hosts: ENC[AES256_GCM,data:0FnrI0lGo3YzUa0oCxIcm/iBhLeQsm+pj/4nzGbnzSi+Y62EVIyKGjsr2Okz2hz/ilXdtwmLOjxSgvPiQJT/SG2TrSlYUk3pnrRulGCrCs94jXgq8zUc3E/gHUy5aDK30eZeqFCkgvPtWCAPrY3ncShvh6XgPZzgBTTY1ofqt98fjffoY2zO3LMdwDiVXLk9Fov8uJ6WP3AZotwrEj7Rur13ILEZ9Kjp5rYQ,iv:vjFAo/zpvVi5vcHNmucffAkO6FGODhDOMignDZ5DhlQ=,tag:sOzmgwgbtww/qdDNrUfKAQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZmtnZVFENGJrajhuWTQr
            NUhjczk1Z1NwdUY3Ri81TFpxWGpCWURGb1djClJIQzVna0hKSzdHdnVaVWh4RmhB
            dUFKOHp5dGp2Z1NmaWVHbkZrdnpYeGcKLS0tIFp6WnlyWUJJeHA4bHg1RWJOS2h5
            eVhuWXYvQUxwWkVFUXZwYlZkWHordmsKTLmfwF0tURMF2hUif4Fwy4INIM94Blo/
            gvDmRsF3O7vAv9LyuO2MNP2jGzDZ91TBtO4qB5MKzseEdvPJYz4+LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T22:35:11Z"
    mac: ENC[AES256_GCM,data:pEPeH8qMBC6Te+FWlkLcT1XXf58FgVtFSEJESOGalpPjpngdFxj6hKsgSJHMwBOSE6eyO88BAthR0gjF8FI2cbygAY+1+qV8vC+AivwPO+BM579DogkKMEO5Tqa2e5ABjqrIQpTRpcZBn0NUKVKHzXWizIX+5v5Pu5/axmOcNHw=,iv:fhghm3OM8ScLmwPdmT9biFezrqtopmE32leADMdgoic=,tag:5sKdXm6fpJdQLPlN+K9y4w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
