apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:utE+GACSbaz4Xdf+6fsDgW7d55w8PS1eUOJHb1hZaZxe73naxk/PnTc9xkMDJKsF7nTEM7w2nm5p6OK1WYU4ZZIhwCDQHxstYhrcGo0CuyHcdsMCRW7eAn2fDezJkc8fR2e3METTBEBJnrJqTBF/WOe4aaMxg/Wqcb4urxb/uQalXO4ep6UnBZaGF3tEuZiE8kxj56HfTtVbMGmZm45j7IokKVT5sa3HcK2qlOuir/AOFdKv3HxWx4OPTZqhTpJbq/gQlMg//23x0ftMBEZQ53Fzs18QUHTdBh/85GsTbvkHL6iMJtxXXxM7aR3l62RZ+pgEmBzTF84Mq3Us0x56s7Ewe3GYqZmkbM1OOuNvFOyDcfzLEpux+ET7aOZDRxUg,iv:1CsT1VabFfHxSxmpWbiRaAud+rSHtoNqJZynd+KcSM8=,tag:s0yJYfyT6Wq2mqBekAnrYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:4f8l4o1v6wZG7ZRd6YQwXd4AFT0dijo4DM5sM3xB5CtMhYyjUC9MB1iaATdXt4MuHRP0ZR94930aa9nIMCMP3caZ1zMRU1roexstKKN7zwFYZMqZoz9ixH14tGH4rcr9wnuWM9mCD/CyuulAvxtu57wpg7fB63fEpNBByINnPqFKsUSPqlse6qOyP3wJv1hmInUpAdaW4N0u7UJj8cYXgJKyXTvIqPcmLHrteUOT4/uO5xLV3mokzXpRRUPR4/7gSFaSn2ld9aRBTyYgpg==,iv:tcZb8QrdElUwjiFemL9I2EOdmSOLtxST2JAhmFiccV8=,tag:hmnNpb//mToruMH2QQeY9A==,type:str]
    known_hosts: ENC[AES256_GCM,data:SzcM3/PbtnGNeYfrKnsriy67giDdfWPByAkTzvwTluTmKqmJhsaqCfj/wPJNZIfL0jH2YvhGXnp7+MpStxR4XeLJKsxZmYycAHGrdunLlTLDev+caJOwkEt/Y0bULFf/i3V1nQjRFZrNKY+lc9sv5pEz7gsAuL+jgYV7wivgddK2z9uIkv+CmiVoQ2FHKr7ZsEx7UL2N4B4ZpauzjQN7daOrYSLYDLfE62Go,iv:KnRWgxUVhz0lSfwpwU6WaRk2rTfCxBFsbOVzFLSEvxw=,tag:7Gq5iFknUqDmA4onIrLsyQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdzh1TGgvTW8veUFNVnNk
            QXJ3QUNOVVQwN28wbnlMY3k4dmFtRjVaUGpvClpKTHpsVGhZNVFqL2liM01oVGU0
            QksxbEphK3dTMURFQzdGb0wwalpjRDAKLS0tIHhFb0tlZ1M5TzlOQjU5QndiV1My
            b2VsdEx2V3VqTjJzZ3BQekJBbS9nZGMKKHUK7KLGVriMdCsAW4qC5LK24KdXInRy
            BRupJUaCkfXCrW0xUqSpcTmrsAwtjFbzb6kEx2TCpCrFwKr7kThw5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-08T12:57:26Z"
    mac: ENC[AES256_GCM,data:SoDoqBgyYWRFiWXUK47sLmTK/IW4RypeVQWaR6aIF7ZLT0WslMnYoKlZvoWdVTnHQHJuuw49PQ7pmoJo3yq/Ei9OMCrece/oCZrAuO/Pedyz6dB786E15CE8sAjtn1TIZd2yjtLf0NwZkHXnaRcgPgU/ISzyC888EuwsmZyzH1g=,iv:CBMlk1w5QFLcXN8/JFJi4cx48dShznuhiML1iYSiqgU=,tag:Jf6771T5UfAWGaLYAxQOeA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
