apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:NDNV6OTVdKrqKb2xG6JKOlu8lxX9tvXWgo0jApBuySo7txMyqGep3zbJh8kMy4SrGK86lelWf+/iwOtwHDaOVxdSfAf0M2TPgPEHi6rwCi5yXZ5hDQjvRKGxy3L1xsr6zvljLwQy+NQlenbIbAjPrtuY+w8RXdy+2djqHvIm3XSeFvpV+7MUvcWUhdWRbILclqqfP6qJUVbkvaWfzo7J+LAMgMsqPxW16/kS8MOIMJtlIGjGTvyi1zsNIl0OidE8dMJt+Dk434SlmjIsku270FEOyXCiQMUop7g+VvKy4aa5b5FqpFlDORZTd5UfouNkGzWVWUXUXwj5AZjGbXvAPl73cogFmTiNR6Jk/Bb6ev55AW2kBtPcZdapdkD8nf4j,iv:ypMWcOqji1YvZIZ3sYzpDBou/dffCKy/MbJZqSniVFU=,tag:d20jSNajTez7yjgxU21R5w==,type:str]
    identity.pub: ENC[AES256_GCM,data:FbczOGHSmFUCFGqDJ9kv375/5ajSkI5TfyWnmu+09yB3tyC2UeHEiC4eLhsAR72XjsVx3iAsABuRdCblSmAygji2GDpB6L0A1/BRgslatUkNhiqLACPSuveDnAGI7Y/jDsGSMD04ktm/jcHHn0icVfhcffqpUeMfQXwRXUIG6uVAoV7TNHs0qjjskQI1fA9Ocg6fp9YHJzcJ4AytlKnj5grpqnmzEjxq151gBEC8MNLdw+ATtkP8kaa4aHDlulOEb97BhJ0dKYNDGusMwg==,iv:aDvhjIpL2HAgrUiVftzJBR6q+jNunfMj27xZRvQP9qg=,tag:SGfoFjv1E8iKWDHkqBMrnQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:EBiOn1pvrBKkpiJy7q2plpPYh92IJfv4UHeB4xXEd9ZHbT60aAGVdw+bNNV0KCH1/Mum6pGuRuEi5agQrcPRmsOipfSbI8MQzlXijlPCIoHAK6kwiM8XfSGPednIc3hT3JCyD0N5Eb3GhT0Yti2WjDhRvcV5JjU8LQ5Zj2FoRTj8JfQw3HSIwfxwtPriWN8MT71ka+HNx5Z4Ms2GFHEFMBtwU8YNJ6SebbXj,iv:t0nLdhjboYZZYNF3vq5t958fkA2dg5ExDBcIc5guPjM=,tag:J5kP7b5j13z+5OA5k94Fqw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvT25LeGdVaGdMTG5Za29L
            WTZsaDI3V1FJMG90WWo1c1kraEoxSTZqcVhnCmM2ME95aDhiSHpwWWJuTnBUOU04
            a2NWNXh4RUhYRFZ4NmlNWEpnakNkUEkKLS0tIEVHQ3Y3WmxOWUI3TUVIZlQ3MnZq
            aUVVWGZ3VUJ4K045MzFvckFSa0tKaVkKNbRUbgbzBXVBop14T+/I7BEIqebGETml
            oJO9pYU+vhVQBhDLdi3q3d/3y2XSdV5iU7GqWCkIWeb/ZIOipT3mww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-15T12:53:21Z"
    mac: ENC[AES256_GCM,data:59DFk8MU0RV2CGjQUhsEKHkExP/nl8w4jg2RaL8THjbu+sBkVMM4pzZEbBd9phiVkIynNliSmM9Aa0K94OLXVf2hNvWrO9d/TATEhIaDE6FFJTV492vFdGAZ8vKrDCUOET5eYl8+5K6t7bV/qxHCG37NsRVJA2C4zMwzEMJ/PzM=,iv:HDRa6YyWKyx5067FaO+ZW2iAb3Z6vK533zKWYB2bfbo=,tag:Y63kOQL7XFf9XzytG/+vgg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
