apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4oZMDh+jD5f8ianHtmjO/vfL3JUm2BNUybrIuBuL+27hIL+OeEyJlxyeV7tRrPRIBdyjrlbTfmFiyCaowz6uYrdUfWB5FpDEoI2wdMpwowAsLJPmqm5Rzm7jrGd15AIJoDHz4SYcsbbKEuWW02PallLDzaZRMiK81aOTnRO3fEuzyQlNQEu0U6scExV2oGu8NqJxd3jzb2tGr/fcMJ0UIHGz2knz9gGNXPCHx3NDpD2O4azzg2XmRZvAH28C8CmS7Jt+MnZYZABc35ZJzNhPGJ71CkYtrlYWgKE29WuShUUx4vcv+t/Nmx2WFsNVgxRmHc0Mp3TpFri7aJlpVZKRgM4UGe5l3GK4P+gyVCxGFJOjmGAhNFzJqAYZ9kCQVdgO,iv:aoXaQa1vkAOU4dIwoQWvn7kB5jebW8oxxlx6zNOjeow=,tag:JcVX10dx30TMSuTQrxnNGg==,type:str]
    identity.pub: ENC[AES256_GCM,data:bFJsje52NzMOVeBHwi+QkeZdEsDdTFOzXcEw9IpHBgzthOQaGxQB+x0iiQUURvyOAkYER/gFDiVY6rBMIj62vBri9hkBrzYYW85fVxke+1zrikKYL6Nzn+KWE6xy+4RfdRQMolB4nENA/lBju3l3hMFHtjaFRkicgA5isULXDSbQzsBiOTF9CDhDO9auLPC8rr8cEv15nkbYxT5YbOrkCGqExe6FhUPAuyh5DRyPrzlGT+iypb2owVHasOpnuWsvGOjzBXQ8bzVNGq1AGA==,iv:Zi0SDVK7FHg7WUXwV3wBbaDzNALCK2nKEGU/xu03FEs=,tag:nz6ul3+Qt1tI6e8JC82aow==,type:str]
    known_hosts: ENC[AES256_GCM,data:PU7tOh7PANMTPs4caVL/MNi2yWY+GYpCs1hFAguov9BOFYTEEiespUn0U7vL78+ELvputbgh8MDswfTBjf+ogaH8Hn0jzbUU7LPzz6jQqQJaxQ7nJH0OVTGuV5GbD/kDnBJiOc8cfcxJHyjq9xZDUGKNaMzFeh5uewZ0pBLa8Z3YMDXn3ZEyGE9PWMAW9KKB8dng8yfzts13EZns8iSWI06+JTjs9OtxLLA5,iv:0slSwf2NKDxHcmJswNe9z4+J0imqJMyhfnfq6JEtmDc=,tag:GcEAOPN/+sKggZWROhYnNw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYjZGSWhaVzBhSXRLMzg3
            bmNJdS9mdjRpK2hiWDNiYTFUZ2VPTm5NM1NnCmszSUZPM0ZFUnUwSkdLZnlXUXA4
            SEV2S1hwNis5b1Z5cDdYU05CTmtsSkUKLS0tIGdLOVN2S3ZMZ29KM0NPMEdLaTNF
            bG55S3J4YUZ4L3RVQ0JvTEFmTG1aYUEKVPiSBEkvNB/Ko4I1goo/Q5ZfFXv2EhLL
            RMhEJEHZGtpl2s8UGQkR2rPah6wE4N+3Mdo4y10BTAxrzf2jYAI2Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T11:30:20Z"
    mac: ENC[AES256_GCM,data:KWrR1yjiNlrQMX4sUSWNfRCcYHNkzQofMezi3z7xidU79akibaWbH3D1Rxnc8RLy5cPI7AL95r6XcXL0c7RQToLQMPRdkNEsMQ/Zg71eC5wPHDqw27BS1FriwsRQ0Jj4MtFYVf04wdMVGxd3UbVhE7LLBwdH5iQDZxV7nbvnWFw=,iv:2Mm231DBMn3Z26GeM9Vj70GS2qd+UVnI6m3mNBi5jtg=,tag:QUfeDGx81YN2VrrjCVnyVw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
