apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:hM8WXovXUrFIbJY3CZ3BUA7p1N232wp5KVqd+TwiRVLI+lCcx/Ni3y7O4FDSoK1sD2K5anhLZZMLcu3KvkZA7VHemkvcefLxLBybwD5eJDCJ0Lda2u+MrLZTxxq0ffAsI31lP9r9dqoBqKMWUwHOreddXHunLG7FjL9PgJx79hj2ogf5V2uCJG4/pkvQPPdnP/tx53w+gO/bcZuLutkIZkpXzhADx1maJghVI7yIkFs08YjvK8cLRm9z6KJr0a7SFwscTt90nrf/RN5u4ES6/DCJQc+VMO+MG0CATzpwSrcNji4L+yQEpUC2h2ZgCmVb07ATWjmMOAEewtzmUTi7+rvGT2J7KLXQUcIbGNDtPCyTUhgZvOSXZcFnKZNP9VIN,iv:GE7KQeVOycBxxPMxEhvQF/qQiek4EKQ2Xd/PoKI1YJI=,tag:a1R7IJFUmTuz6UTjcZCekA==,type:str]
    identity.pub: ENC[AES256_GCM,data:+X7uvqXMiJFhVzcsCst884RpvBdjMFdo9yJaeENryQC7QMpc2F+5v9yp6ZjWUUnMGz+uEjARxu1nU1fP0wmKtkn2cDwZ1vG8g6hjvDuvHQG0K/77KGBq/TQVfCUicRHy05pnYr1pOsbkWNazALdOH8zTqJ+gM9PXpunyVGXZA9BmhLGK/4b+RtEYVs9O3y0Z3LSUh1DIlgORsJovhBOCOTXlC6DgJCuzz8x9JP/VqdEB3PTLsGbB1cHfpONnl2UnNTPYj7Ru1YNZmKgrmg==,iv:o7DgLnod5fDGgbZR3EB1nCkHm74+jduFWxQFXGhseeg=,tag:t3rSHw+Uu3didKstZQDGkQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:/Awl9HscSDBAmLwRwuZP//UaAvrrL8nhTZeFtqEg17kfrLKjNcQx7lqz/Q5w4AyZv5OQy/RU4iamT4twRsuqjFTVXXa6GJFZC3P1T5ny7og6LN8kldt2Lo7ZY/IWhWaN7Sp+JgzLjij0gbjqf6BoYA4UyPAiwMEYfR2cdvisfALLqYfwmvAfM0vK09D26Ys1SPcnvlB7gXfRiziCOtv3Zo8U0/kKN5TztAO6,iv:oy3iOY/O0cKALmkpeuhZqgiwC8mWQxLd5jiXEtxRDzI=,tag:Y9TNVT1rYvVDl4iAm0lOMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdCtkVUFqdnRhODV2Q0FC
            VFEwa1Uzb0gzYWc2N3JQRGEyT3cyZDJjNFNjCklKTDhCNytpVmI4WnplQzc1SE1a
            SnM2MUdYUDdrYzdjaWpRcXhGYWk1VzAKLS0tIGVZTE1YMVBValdXNGs3LzFJeXJB
            eUl0aGZqalpQZW9FUTQvaVZOWlNzcncKmXcIhv2tJW7gCmrwO+rny+ijEF7BcEAR
            +QH9UWUsSEsFw+0cFuPzhywDjuAlYq0+twWQFyj8pICgZz460P/1gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T12:05:19Z"
    mac: ENC[AES256_GCM,data:KOJFEy0U3Lo3YNGcXIVmB6VN1Bsr3w33JjV3z/vilGbuVWh831wx2u6objUvEL5aBYoJ/hE3HKpV/bUGeQ/giP81wi7ylhTClyqE28zr6fAhZhKzl8AzRbjzdEeSbUKJFlFYkDX8c8mUX/3w+jZb044sw52uT3dc2VQVt0VNcNo=,iv:8bszgb7lYnf+EPBw2WN+1ShS5l2tvXIraO70LiEXpqU=,tag:9AwmMOc+ZskJYMnchTvhDQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
