apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:T9en5eSnY5cJDKt9HK5U1dfCmcJRBZhTedNuT0wZkVfvagR+TTT19zvelN4T0KudIay6CXTFBQG12oLxiMPdwYjjnub/o2Aoo4iR2WP1dIDX0sXDEJl5r2YCTcUpHmV6HpqsJygNovx6yNudj1Ver5o8EPNf1SUVvEpYz/YMLS0YRNtFJlqKqKBCDsXoXvXKcu2eObdx8toit1UQFJo2VrM0gG3KkksjQSq/+Zg4cshJyHmly24oo4o17505JqK8Dc3i12xCZ3y7I2VDnmcuXCdmU6CUZMWGOeakphKRdxwgHnN97Z3WKAg0oyWLDKTmbmtCw1Wgmp6obNZ5omwgxZatIWGa6ir+JxVE91hZoTZoRxiyQzLEP7l94L0hJ7W9,iv:CZ7HfHGWZkouc/c/R5IngbF3wmgkgJxW8i5lWLh5BwM=,tag:zVQ2OSLv3ZKEcNfo2agyDA==,type:str]
    identity.pub: ENC[AES256_GCM,data:0LAzV9Z9bEel3LwUwoYSZrpqBv/StgzRak3UeJl7n3PFVdD2se7AASum/rBb76MfJ0LiY4ceOPy45gG1uROEabzFcCilt60izLPFjlKISCKSKfZVq8rd0jdy71wC8ZArvWdKMX+833ywhYprseefDOzAh5LJssXHwyOpbu0Nib/uQAlcQPQ7nLrqrDHBqb8fsHq0GyIXc7Hz1WVTNsbTPgNbabTkR7obGWkrnMHSZRn+hoy21kY82m3VoXTogrKDles+mofS1+G4Lj3pzQ==,iv:VDh09g8+U6RpNR31Ux4mnULyN5v5VkZKzltt/zTj9mI=,tag:cSol5Oq38tv8Wm16Xv8WCw==,type:str]
    known_hosts: ENC[AES256_GCM,data:6H0pTKhMqJutNW3tXDxP48ygD7Sg2YKBpeq66nfA7p3+hPsqqwvtItSMqktnsLEFx6Re5AX2HgIvZzIy8yT94mVarAxb9SXw5bCCy659Nkn0B89V89+AMExIPr451ooQY4CyR9lO+c/k9M4FPwB7Eb3y0vr8grw7N6QI8H5C018OtTyKHK15XKzbvPEB7M72CzZe/00124eLhdpASwIjrmDNw/wp2sX8bhIP,iv:D4Hc47ORLUKkeO46TJhVjT0mLE4Xf1WzgA+Y8kDoVjs=,tag:c8uKNOa1k8PziBlbEOqBbw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RzliMk1tYXRMbU92VjEw
            QVRlMzhkWnZLY09TWlJSZG8rWkEzUm5xNlJVCm1lbFBHdXJ5SUJDWHBUT25Ba1dl
            QmI1TzlmcXdwWmQreHl4cGY4Tkh6VkUKLS0tIHM4ZVZjaVUyY1pYOGpNMmdOL1E3
            L1U0bWdKTjdMckIzVnJzNTY4ZTd4S0UKeAtD/pq836MNlpyOtcX5iEkxkEvEmTBa
            RMy3Y9s1CXg2Zgsz+WJUm6qB+K5vD5wS6d8jG/lFibGhHD88llo0ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-05T20:00:24Z"
    mac: ENC[AES256_GCM,data:oqkqnwwhxfWO2SvXCmMPZvAtz7/ZhgsmDkYHVBB+2xClUvLDZcUzIKb95gPhLpaGD3COa1H1u+nGWKTlrpU8MjCIUgNcmqptIDVQgzbgUSIrVYu/fgvDyDS3fH/MoMRy5OUbjYuMD1sffnKQj9ZvAPDS7e/knlBDeGIMy6i6btM=,iv:WWn62xOtIpvIkIr7/S1DxE0aqocwtPtKUuNJow/x2c8=,tag:vAPUDqCA2vmtX5jQcrySew==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
