apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:c0awbhXRqCo43t9s8j/owyGTwR20pJLSZt1BQ3hSwpIqRCOdLLF9ID26JGqV37rOXLqSCWWox4rFHdatSkcBjru3PIIj9mGA/dD/gDQALXGi7mXAIS9SMz8/RURwtDt6/nDy9FVw6ObApHWY3tG2bzP/BLosxmmDU3SdmGGfnYHdn7LZJtnAqRMH7h5ieuknPK7TSwomv1mvCIAmChvXsXne9/CKuje+1UTDtv2i4NG7U7Zk1rxPF90oF2Md9afMOPON3CJSnN1K370hhaLIn7zuVDd7fOFmglJzCSobUnWslEYQiboR3VOM86hfTfsM64b+x/vDi6qwb7jkP9ZCc52WEcGQncQ149pzHZjuv7SDfOL7IYeH01dgtCZY9vUP,iv:hFLr0JHiSr7a0h2WHcYTF6rDMTdVTIPQ0Q3QHoUGJu8=,tag:1EtzH7Grj2ksX6cahMV3pw==,type:str]
    identity.pub: ENC[AES256_GCM,data:tDfNhwaw1WP6HqYGvBA/2LuM5QBEGGL6ZSx7pyn+zOeYi2UrynUT/CdKeV6UAlmVhS0w9GSVk9m3WFAukScj//GonEMPU9xYNU5D6RKmCrjkm9qrMfqegSPV3rG2fOrRJ8vwaJssUHG4O8xDMjztOLT0UQ7+P2I4iwjxXiHlHIdMsI7fVXv1A6441Kd83cpo/KTOr+HUnWeq4BlxrG3OAUsSLbBndzgRECZarotzW9EqNB/AP64QCJTkp2av7lBAAU9rbmJVblANmPeA+w==,iv:hTy4uTkMoZj8bouARniq7rC2hwIubkLX3ma5ZAnzEEs=,tag:OGPizW6xayOHn+rBB4aDbg==,type:str]
    known_hosts: ENC[AES256_GCM,data:7ZIWjdUH2Nv9SQoAy0pWMYUbSt+NclaUoG2UCwY8PSFacVo8lacS/Ed36GyCRC0boAZQuAHaKU9j7ZrrVPyZmYKirltPiVRfu9F3xUEYgS1fWNnMzHNbhx4FAHYkiDp2Sd/v1EpLER4Rgm8eHZXSZpkzDMTxWChe3ZGit8UENBVXx60hgORMjj87f0gEaJSIUPQUrLS02I4nLvUlNXhOyttOHCvDSkzmAN4Z,iv:IgpCmsMDP1ZxE+Xs0cTETkqupw7h9OxjEKAPfa9gfBI=,tag:nK8RUHFVXtpyqMiWuS9ocw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dFl5NHZCT2JKb2VvZFcr
            N0JJNjdPSzBVTzg1VmJwVnNTckgzQ1RwWW5VClJ0QUJTZ0lwSXRGNmE2ZWxVQm5x
            MjJ5d0EwcnozWHV4QlR5VjRpRkFZSHMKLS0tIGxWdDEyQitIcUxvb09BRFJGZ2ZX
            NWFTdC91TlN2T1ZzaGZVM3BBYzVtdEUKvAJkpTiTk3BGci5oLFhxb/BVxSB3HoXi
            hyd43LpcicxMi1DEpx3hvcxqaoJ3Pl+yznSaAOgTSKzW96VDpXKRIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T14:23:43Z"
    mac: ENC[AES256_GCM,data:rgb/kifEsju/Is/S1BcJj4Tz5CnQlIiUV8gmfvy8jLrNn8mHYbCqPOctsnpk77Owv/mVYxbQaIHV95F5ZBXmPdx/NyXreO+1GdIlmJw4ektL1Ujwgc2K2jKPCmGsG8ke1Rog+JzYnJNo1ykfNfv6yAJ64bNzb8KV8/j1kJT93+s=,iv:ORIydKHq5zMoPJ205mESJbwgD8pweHTp3Ux7no4DrrI=,tag:ml2w2QjRPuURLHZZygx96A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
