apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ML4RJVz2TL9gbHtsqm0a5/PZ0J6SdSP74/gJ9FBgC2bLBcX8yfc1C5f1OluKZ5QSL1I3x1Xh4cprGf2GdFcXd/0jXfsmc4bPXJ+23CoAmbXfaP8cpsgeDYwGxQcUopA40x4UtGNSFLQN9JismbuLu2qcgPGNZC74WzzpMu34S8E0CUxBRWL2SCoaKnjfs6C0CO6qcKP9w8SDpzf6S3Ge9DGhmGRKWxTrR2i3k4DdMa0pdpf+SpY0mjLx7dPFhriAn2vunuGHhaxG1U7ZCdQIcov3a8UDngrR7MH9C2nMPIqOVTxTjck9uqA6lkYXjR4HnJnZfdmAgCYGDc9i5zl8uv5sZpktR8HDy/CkEV53Gl3G2SwQdg8Gw6xXOnO40hN6,iv:hHm+0KPPQEUyw05Sb1cLA6uOq57pjrLNX3RTYVNxAvg=,tag:kh8SzpDEN41klHw1WBq8OQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:dSykySgNC6h2sjpPKyYSXnKC4ltFAAWF04F/rTJc6yQ5Mm4gFToDJM9j7sbhz1WEnE805RM0EhGPvI8RZSrI8evYjKRkZU9EoZdic9n4VqZNWegiOuu7VAQgu96SPABfB60FCug7ydXtjP7m4O+6cMuKjf+ZAKI66lAWFp/ry8FPb4FdsMALMdLUa5q3k3Qj+k3RxAZ+sqCqNehd6/04SRGvXIjNGCbzcR8bblYevBDnAFkdJn3bIpUehfSop/OmXjCTnH2p7AmQN5CwEg==,iv:ulbR1pfy7il7CuJg38lCCznL7pqhhs1dadE76UbWIYY=,tag:SkaptnD13aItBBcjrDJdLw==,type:str]
    known_hosts: ENC[AES256_GCM,data:v+Z9rqJk1LiwB1mZBuDRhq8p1ZPSbacuThFcXbSI3OgBIL6eCRTbhjmR2nsdKCOsaE1qowL15MxBJymXWYYPbq4e8kaoZzikAXUsyRknq90OpMrdxzgF0HYbAGdjMTNr/Biv/WLaL76wmxmsPz+auqAUYEmOsGCYm2o8AkQ0HEDrLQVcdccjnUmULRGLvGeY2ijdeusRlJaBoP3unKXiXOCDYvYGxK8spsnD,iv:kKH611PCo6WMR3uSIBxZ9fpYKVdoYC7G7ewekxBHHLI=,tag:NoyTkh3l2ph/PzdDZuN1Nw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlczg0YUFLUVVqdjlSQlA4
            d3pmRDZOU1NHT2d4SWRpZDV5V003S1BENDJVClBNSFgveUVIRlg2SWdXbW1NRzEw
            UGFqdWs4dzFCK1ZGQTRJQlNqRzcrTnMKLS0tIHc3RlFQbWord3I1TVFkRGhQMzhw
            WG11c01oci9ZQXZsQUl6Y01lMjM1K0EKkNSJVAKurPVZCHQP/oxyNfOMtX27pqrJ
            rSUxaFMaJbatxln+0Gm+MzRCu+NzgdL1JW4DE3Tqa8st5eCly141IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T13:47:52Z"
    mac: ENC[AES256_GCM,data:okpZH2yqwBt2LWJVAyEu+W8mRzAx4STMV7TGVy7Is7Hr5jcIKcWkugBvq32RIWKrJEClx7ZFWMfTs2TgJRRGaXTPHlZbz4Sx4aeQ75hbcrum238vuOPEb6K48g39/dNqiIy4Fb7U+IFDij7SSzc3W/pShSBfm8TdSzKYjrIc+ok=,iv:Muc7w/1vJdnRtyF2c6gxMbrEPoiWYaaVovVf+taKi+Q=,tag:nyIWA4BBEirXEwgWx0CZVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
