apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4MP681uK5fVgwNczBv2JxfPP2qXs4RhCxi/BYHRrvFy+GwHW1az5h7CgGfwnMBX5VAOQ5f/TY635jhKsIeZj5EX1KsxaAeLAIjr3qshgCEUjVHWng5+2c/Skk15VkMazpSRByOyflQW95rJxDoD6x92+iG+Xy7P1clQkhqfYuo7eiSGFzhAyeW/GmsJW0DkUgNIT3Qh+QeDqqckeNUKsXcKGlC4e0Sx2ugNonB1kXeQGPgWWKYyCR37h7WwjL+Ko/pYaaBjBeHM+XL5XxwpHvKaaOLWRSXL6ZvukH163+Raj17QkUcNG92wrIfCkpjYGKt9JJJf4XArm3tcRoQ/OhAURPT/dixIBJTz1AZQNiPO3X2eXr119pvszicLBmlOu,iv:2BnlfOgXBUMpfiJ/Ca5ewfcKGLfyW/TBAVvMEQfuoW8=,tag:jNFLuvKKpH/v1YnfFLN2Yg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZQo5M0xOrzNfYc3xPAqBKBgAxnFNWl62UTs8g/oG7Rt04TbV1pMlWOvVNh6Ipm1AHN0kEsHQ+TwaCQ79SDv64tg5qc2pCSBlf6h1fk30yY+FEQZUZH9nK0AMmjsx42EiBI5wO1yM1mk2k5kGWGwx5fL69ChqT5/N8IC5/+e0w4IJJ2Duv6mzvNhEFkoFw9prwRgysxitc5Rah1ZQ5/xeH8mn365LR+t2W2fDuKGlC/cRyA+7v4hWtrtysXmCh8xBkf23i6bqeCrRYuOY2A==,iv:ai8jKB+ct7qb2o3bRIFKyP//DsQ0+IngTuUMqaWw5wk=,tag:6YQozuk+1oMpkpudozzJwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:D3yw+ecLLXdmwqgvoJnBxhj3L+NObMd4V4lV1NPMlRFSRvESsHNr2TG458dotW0qSFLJ6k1VC5Qy4RJ9EWQ2LTBOK0MUb6a4TrXb8CJ1CVpjKFnNUvui404pTgICwvavonHSeiTkFEtvmkw4gEsigS2I5l7qTpdWSPObwDR1WjpSxRKqV/LGF2PilqxpI4zjGckmpgsgZijBRpqy8C3P3dEP/1Rbf6R/zJBF,iv:J+MNLetusoq/eZC4K4R7ISxbORoKg4bk7weCY4nWPWM=,tag:tpa3u6Ky5kFY4j6aLu190w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRWNWMHBnZmk0YW85bmRC
            SVBkSHNUdUpoS0JOUEZTUkpwK2hXNU03RUQ4ClFOdXhqS0lBTHFnYS9sL0hkVkVh
            KzFONEZScXByeXo0RFJrRi8zbUhKNTQKLS0tIFAxaExiT2Q3MmN6dzd2MCszZlEv
            dDdaWWt2MUYxRU00dU1HeUZFdDlqeGMKGqvDZBqFrbrQgPU4+YzYoq4mhD81zmTi
            7a9lC7gdepXMx6gDdUpQ0KYnIKq5OCKiq+O5/sbVViIbrDDuITgwZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T07:29:53Z"
    mac: ENC[AES256_GCM,data:jIdA3C9+FdCptR3gfx8JE8mVfzZ3ejG39J3jLnj3kaYC20Aom7vbBadCW4uC7CBx0RXIkac9s3kndQJFG518HGavZ1N4GvEP8aDWdc4FmFpKXoWKh0x42xnHQ7fUH6i1sjpx+R2EwKakN7/7VBxtwmTFC+v58auaT3doFRbsFj0=,iv:ZI3ak87exPWgzYcqsrjwtIVw2BhEfSayd9FfxSKiYUw=,tag:QE2GYGOVjySOjq+dEPjc/w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
