apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:i4LW7/F43IEC1LTez8CygqsX7Q6Pr8QTuaETzEIBX7ES5t4EIGYW0C9VS+zujF3Y/7j3z5SPCIxqORM7Ida23QR7nU843Br2dGtj/qL5QtcCpw3R4ZydJmFxxYz3X6F+Ia+v0RHWw5XxJi66e0x3qus7mHpB8wMCMMWT9uG0BfZGqR9olQGGoENqoOuNkgcL9AkP9dAOvh3x3lzZ2KFNF0NDLW1Bla87QBYPMTPQANc+nEVdQNTk4rRdv+cKrxO5RiEOQ4UAJQFc52CpO/3AbiXzH5/oc7SQlsvyD40fkME70sH1hvYMtIV1Z17T+2jIQdWwa1EkL5+t1T/wvvigvnN2muIoqX9pYQ4H6GNGO8q8M9i7i+9j9ONTzygm4vko,iv:Nbw5EslKp/EPwVW5+lMeP9HA38Y0FqEDRz1/bxfJErg=,tag:7mIpwukDc+3MpUGqs7+LAg==,type:str]
    identity.pub: ENC[AES256_GCM,data:LinjvDuvzUs63Xs5JSR+FgH/s0dlhR90yxY/OxIcdBT0mJma10rB7FGkUO19PipUl7L1N+eFtPngpt2hoZcp2ZlApT0VHi9YE+PIxAZhQPjEs/t3RkL9xZAFiAK/1XwfmpJdHQLgi5W070wsfLWLppW4ikJ/oFuX0pHAzY0ps+iOMohVTbQRqkuY9OUETiSloeqaNwEJyL+zMasv0J6sBsAeaJqbgWFARr/KO4AD+s1xS098gi0H4yWHfqluKpEvEeFYaQ+ttbETGiQAkA==,iv:YsvQfuo612PqcYvAEL5Z71RCgddR7YKjjU5lVKyFEqA=,tag:+icnaX2yR/To2JtiLYhhjw==,type:str]
    known_hosts: ENC[AES256_GCM,data:1G9KxL78UwVacPA2tN6zzGEp7+U+bwWkUzpFdOIQDueb/0FzIoRv+LCBge5k6ZQNH7wXBxZSQ6OHBwpYx/YSBGjc4kAlJJrTi57pMx0arGZ9OSpoRMOv33vGat8WK2nSjmDarBEYpaTd6xy8vrTgnjC07084gNDne1DdLG7QU6Cxp3sJG+VwyRn7POJTlYKq13NcllSKp44pSPz9y/liO/vrwxeiAQehA7/B,iv:CRRiCPJjxYgl7a71yuasIaEFH+8sdas5ZcwaIjulxyI=,tag:0rDWAI9M17Dp5Fv12LUG1Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVG1SV21helQvZndxaHNk
            d0JsOE9CeGFRemxsb2ltU1d5RkxSM1FpaDJ3CmwwWnhSak10eEZFVXN6QjRUWkFH
            YjRMakEyYzR2YTEvNGZXTEFxSThheEEKLS0tIEwwRUhQTnZzaTBRbFNWeGNTN251
            RllUUFkzU3ZFNk1rdXhxWDB1V3RlMzQKZ7bdGv1OeJ5t7RBcD3bn1ijJ3GFd+QYk
            4QoT3qcQ3Cq8eZtRO0xOMKej9tfa6Q6h2Nb1JJu4zDiujHaMVgPrGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T11:28:33Z"
    mac: ENC[AES256_GCM,data:RluuhwLXSDeLAKFByt3H9iWjwgbyHBis3X+yG9LwZGBdzs+wEov2CAF8GYFce5Ebp1k4JS0VjLqv29hvypzFK+M6qcAT1EUOHy7OW5wzhQsOeNn4EN6SDYg3J9/r4dhNpjMxAhY073DT1l0r6TmZbGQTwBwa2AQHaPrLnLNTPhU=,iv:2LPBvwxfA8HdOMfc84rIqbIL4hz50SAWAPahIWMhFBM=,tag:Gwu30Icy34aXfcOAEjjYlQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
