apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tM9brV/T5Kq7uVhGX19pBRzHiPbEGJphaS4jOC2ol5dbhiExsGZOktZaDYjsOgbWX88DloZqjantEoeRska2yITGnbXIwJI1A9okeuSaJ9mjaYWfZ8LyWQcYBNY8vyVyyK3+skZvijoCuXeW/o2PIX8p5pYqClpqNhugAbrnlB/IQQ2wKESVGT1gn8m3tICMFo0tCDwFNj0nfROVm1K/KJ6ySlDbGOGZtd0MTpSTD1u9goZ0r02isyoEdOGlDGM2Ue36JUuFn6EM1HpuA3497+8lDwaHQkmw497lxWQSt6gPQ3F9UEvkcYnEy4aTTCU1KLs4B3WNBK2voRr0/cpnB+EG23h9P6PtiuCBcmIzGxjr728diA64BYliGWS/P+4l,iv:zBNzA36maEZoQH+CKxO4pDdzwN9kF5LyvQHEj/4DmGg=,tag:rGxFjGBBCGIEYYfTWVMPEw==,type:str]
    identity.pub: ENC[AES256_GCM,data:BNaXJyo1rFeaO6DuriZr0wR25LQmR1C5L0SyYlRhJTMbU+bimXiuXzYLAziYHAh3fZQcf88EfLplT/zdcTdwBFlB9d0UUJKCvpWXt/q2JaK1jLrHiUlRAmLHKa/kWwHv7BIBRR0Qh3+grSefUbb4tUh/KJDeY2whW0bc3psCcFeBuLLvAlDoRbD5zYNLhR8/VD9mulK8+gQcfdKwEiesd/2gGQE4RbCFhminM/hvkXcSVY2f4fPeZ9oZgbqthTvqlSVOG+cIEBx8uKSVHQ==,iv:doinmpz4UMRFBx0rcP7WcLe+0e9xNvdixg6YOGRRhKM=,tag:gYj23/I7+Bv7ErmyFqTxZg==,type:str]
    known_hosts: ENC[AES256_GCM,data:TooWsfl2et+DIuajGXHSMgqwQKgClD6EFJII9PkbY5/+bV8Mz7ks7mnfEmR67rknYuO01QxjCR/Kolq+wsFpKUi4yRVrtymfQb/Qmw7YwRd+w+KmbyXs1u1RD8Zy3AVI2ihDlNUcC78LXy3G4FPPpIU0/nGhPfcyRSaELW2jwAUt3ME3QpklMJfP/jBAwdyhz+4kXfVaPZZd9hYm8u7pwjZuptY5OGz1uInD,iv:I1QSHlJcj5nSGsz+JHoRsqe/6SgIpve5BHopeTzkwT0=,tag:3PnxJKDpOuEmKMcm9Fb7qA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1mfegtkhyz3p4um3uy0v66l5fwjpsflnhu85l7atjs6n6sr3nl9asfqx0mg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR3FkaUMvQU9sSmJGTnhR
            Y3Jrci9QQkF4Z0hHTDl4eU1qaFRSN2diVEMwClRiYlhVTmx3M2tXTXFyVzJyRHBy
            UklxeTFZN0luUFFnVDZ6bkNvcWJ2TkEKLS0tIFpWdG56amNBZnBpZSsyOXJoSmpN
            d3ovemZ5Q3VnWEF1VGMzWUhUTko0a0UKdRVB007oqytd5sYE+QpzSNVB4a2v61dM
            ylppji7KvYAVJGG7MNC5VFX7sdeqeAcgE+jrtxIlSFaV3636WC0uNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-06T06:44:34Z"
    mac: ENC[AES256_GCM,data:awss2fOVRysJUKludMdqccuy+Fkq6v9bnR6BfKyWFk9SWpQuScYKfQJd2TzXUPpiJPCMqDiZz4rri6PlaX0wIK5pNYFzFi2QWF3ZLq6GcV12mHzZtTN3egrcnxuGG7098kiB8t+nL+y3He0aAuu4jJVYtrm1q5LOPB+PfCcgsWE=,iv:dnEGFgvLpfRC3kLRaeR3NvmlySeghX9JFkirRqw49Lo=,tag:3l0VcH4ua7HbtQqzO8jLXg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.1
