apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smokeping
  namespace: smokeping
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: smokeping
      version: 13.3.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  securityContext:
    capabilities:
      - NET_RAW
    container:
      privileged: true
  values:
    global:
      stopAll: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: ping.${DOMAIN_0}
        integrations:
          traefik:
            enabled: false
          #auth
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
