apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crafty-4
  namespace: crafty-4
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: crafty-4
      version: 9.5.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  timeout: 20m
  values:
    global:
      stopAll: false
    service:
      minecraft:
        type: LoadBalancer
        loadBalancerIp: {$MINECRAFT_IP}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "crafty4.${DOMAIN_0}"
            paths:
              - path: "/"
                type: "Prefix"
        integrations:
          traefik:
            enabled: false
            #auth
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      minecraft:
        enabled: true
        ingressClassName: external
        hosts:
          - host: "mc.${DOMAIN_0}"
            paths:
              - path: "/"
                pathType: "Prefix"
                overrideService:
                  name: minecraft
                  port: 25565
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: false
    resources:
      limits:
        memory: 16Gi
