apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homebox
  namespace: homebox
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.truechartsoci.org
      chart: homebox
      version: 8.13.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    global:
      stopAll: false
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: inv.${DOMAIN_0}
        integrations:
          traefik:
            enabled: false
            #auth
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
